Repository ObolNetwork/charon, pull requests merged in 2023-11, with the labels that each got.

#2670 core/tracker: fix inclusion checker bug
  core/tracker/inclusion.go
Labels: merge when ready

#2673 cmd/createcluster: fix pre-gen builder registrations
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  cmd/testdata/TestCreateCluster_test_with_fee_recipient_and_withdrawal_addresses_files.golden
  cmd/testdata/TestCreateCluster_test_with_fee_recipient_and_withdrawal_addresses_output.golden
  testutil/random.go
Labels: merge when ready, v0.17.2

#2668 *: convert to uint64
  app/app.go
  app/app_internal_test.go
  app/eth2wrap/success.go
  app/eth2wrap/synthproposer.go
  app/eth2wrap/synthproposer_test.go
  app/priorities.go
  app/qbftdebug_internal_test.go
  core/aggsigdb/memory_internal_test.go
  core/bcast/bcast.go
  core/config.go
  core/consensus/component.go
  core/consensus/msg_internal_test.go
  core/consensus/roundtimer.go
  core/consensus/strategysim_internal_test.go
  core/corepb/v1/core.pb.go
  core/corepb/v1/core.proto
  core/deadline_test.go
  core/dutydb/memory.go
  core/dutydb/memory_test.go
  core/fetcher/fetcher.go
  core/fetcher/fetcher_test.go
  core/gater.go
  core/infosync/infosync.go
  core/interfaces.go
  core/leadercast/leadercast_internal_test.go
  core/leadercast/transport_test.go
  core/priority/calculate_internal_test.go
  core/priority/prioritiser_test.go
  core/scheduler/scheduler.go
  core/scheduler/scheduler_internal_test.go
  core/scheduler/scheduler_test.go
  core/tracing.go
  core/tracker/inclusion.go
  core/tracker/inclusion_internal_test.go
  core/tracker/tracker.go
  core/tracker/tracker_internal_test.go
  core/types.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_test.go
  dkg/exchanger.go
  docs/architecture.md
  p2p/receive_test.go
  p2p/sender_test.go
  testutil/helpers.go
  testutil/validatormock/component.go
Labels: merge when ready

#2680 core/validatorapi: fix get validators method
  core/validatorapi/validatorapi.go
Labels: merge when ready

#2675 core/bcast: fix builder registrations delays
  core/bcast/bcast.go
Labels: merge when ready

#2684 dkg: remove keycast dkg
  cmd/createdkg.go
  dkg/dkg.go
  dkg/dkg_test.go
  dkg/keycast.go
  dkg/keycast_internal_test.go
  dkg/share.go
  dkg/transport.go
Labels: merge when ready

#2682 core: revert core interfaces
  cmd/createcluster.go
  core/corepb/v1/core.pb.go
  core/corepb/v1/core.proto
  core/eth2signeddata.go
  core/eth2signeddata_test.go
  core/fetcher/fetcher.go
  core/fetcher/fetcher_test.go
  core/parsigdb/memory.go
  core/proto.go
  core/proto_test.go
  core/sigagg/sigagg.go
  core/sigagg/sigagg_test.go
  core/signeddata.go
  core/signeddata_test.go
  core/tracker/tracker.go
  core/tracker/tracker_internal_test.go
  core/types.go
  dkg/dkg.go
  eth2util/registration/registration_test.go
  testutil/integration/simnet_test.go
Labels: merge when ready

#2683 *: update license
  LICENSE
Labels: merge when ready

#2685 obolapi: update publish lock timeout to 30s
  app/obolapi/api.go
Labels: merge when ready

#2686 app/version: bump to `v0.19-dev`
  app/version/version.go
Labels: merge when ready

#2687 app/version: bump to v0.18-rc
  app/version/version.go
Labels: merge when ready, branch-release

#2689 *: cherry pick 2685 and 2673
  app/obolapi/api.go
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  cmd/testdata/TestCreateCluster_test_with_fee_recipient_and_withdrawal_addresses_files.golden
  cmd/testdata/TestCreateCluster_test_with_fee_recipient_and_withdrawal_addresses_output.golden
  testutil/random.go
Labels: merge when ready, branch-release

#2693 eth2wrap: fix synthetic block proposals
  app/eth2wrap/synthproposer.go
  testutil/compose/static/lighthouse/run.sh
Labels: merge when ready

#2694 *: bump to go 1.21.4
  .github/workflows/golangci-lint.yml
  .github/workflows/govulncheck.yml
  .github/workflows/nightly-tests.yml
  .github/workflows/pre-commit.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/verify-pr.yml
  .golangci.yml
  Dockerfile
  testutil/promrated/Dockerfile
Labels: merge when ready

#2696 *: cherry pick commits
  .github/workflows/golangci-lint.yml
  .github/workflows/govulncheck.yml
  .github/workflows/nightly-tests.yml
  .github/workflows/pre-commit.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/verify-pr.yml
  .golangci.yml
  Dockerfile
  app/eth2wrap/synthproposer.go
  app/obolapi/api.go
  testutil/compose/static/lighthouse/run.sh
  testutil/promrated/Dockerfile
Labels: merge when ready, branch-release

#2703 compose: fix version matrix test
  app/version/version.go
  testutil/compose/smoke/smoke_test.go
Labels: merge when ready

#2702 app/eth2wrap: fix error comparison for synthetic blocks
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_test.go
  app/eth2wrap/synthproposer.go
  app/eth2wrap/synthproposer_test.go
Labels: merge when ready

#2705 app/eth2wrap: fix error comparison for synthetic blocks
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_test.go
  app/eth2wrap/synthproposer.go
  app/eth2wrap/synthproposer_test.go
Labels: merge when ready, branch-release

#2709 eth2wrap: update interfaces
  app/app.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/eth2wrap_test.go
  app/monitoringapi.go
  app/monitoringapi_internal_test.go
  app/vmock.go
  cluster/manifest/testdata/TestAddValidators_proto.golden
  cluster/manifest/testdata/TestGenValidators_proto.golden
  cluster/manifest/testdata/TestLegacyLock_cluster.golden
  cmd/testdata/Test_viewClusterManifest.golden
  core/bcast/bcast.go
  core/deadline.go
  core/gater.go
  core/scheduler/scheduler.go
  core/scheduler/scheduler_test.go
  core/ssz.go
  core/testdata/TestJSONSerialisation_VersionedBlindedProposal.json.golden
  core/testdata/TestSSZSerialisation_VersionedBlindedProposal.ssz.golden
  core/tracker/inclusion.go
  core/unsigneddata.go
  core/validatorapi/eth2types.go
  core/validatorapi/router.go
  core/validatorapi/router_internal_test.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_test.go
  eth2util/eth2exp/attagg_old.go
  eth2util/signing/signing.go
  eth2util/signing/signing_test.go
  go.mod
  go.sum
  testutil/beaconmock/beaconmock.go
  testutil/beaconmock/headproducer.go
  testutil/beaconmock/options.go
  testutil/beaconmock/server_test.go
  testutil/fuzz.go
  testutil/validatormock/propose.go
  testutil/validatormock/synccomm.go
Labels: merge when ready

#2727 scheduler: check for activation epoch
  core/scheduler/scheduler.go
Labels: merge when ready

#2715 cmd: add custom testnet flags
  app/app.go
  app/monitoringapi.go
  cluster/eip712sigs.go
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  cmd/run.go
  cmd/testdata/TestCreateCluster_custom_testnet_flags_files.golden
  cmd/testdata/TestCreateCluster_custom_testnet_flags_output.golden
  docs/configuration.md
  eth2util/eip712/eip712_test.go
  eth2util/network.go
  eth2util/network_test.go
Labels: merge when ready
