Repository ObolNetwork/charon, pull requests merged in 2023-04, with the labels that each got.

#1961 app: add readyz error when BN can't sync because of zero peers
  app/metrics.go
  app/monitoringapi.go
  app/monitoringapi_internal_test.go
  testutil/compose/static/grafana/dash_charon_overview.json
Labels: merge when ready

#1988 dkg: fix race in sync test
  dkg/dkg_test.go
Labels: merge when ready

#1986 cmd: change to mainnet by default
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  cmd/createdkg_internal_test.go
Labels: merge when ready

#1990 eth2util/rlp: add fuzz tests
  eth2util/rlp/rlp.go
  eth2util/rlp/rlp_test.go
Labels: merge when ready

#1992 testutil/compose: hardcode testnet
  cmd/createcluster_internal_test.go
  testutil/compose/define.go
  testutil/compose/lock.go
  testutil/compose/smoke/smoke_test.go
  testutil/compose/testdata/TestDockerCompose_define_dkg_template.golden
  testutil/compose/testdata/TestDockerCompose_define_dkg_yml.golden
  testutil/compose/testdata/TestDockerCompose_lock_create_template.golden
  testutil/compose/testdata/TestDockerCompose_lock_create_yml.golden
Labels: merge when ready

#1994 integration: wait for beaconmock to be up before starting teku
  testutil/integration/simnet_test.go
Labels: bug, merge when ready

#1993 *: speed up keystore tests
  cluster/test_cluster.go
  cmd/combine/combine_test.go
  dkg/disk.go
  dkg/dkg.go
  dkg/dkg_test.go
Labels: merge when ready

#1996 testutil/validatormock: fix concurrent access race
  dkg/dkg.go
  dkg/dkg_test.go
  dkg/sync/server.go
  testutil/helpers.go
  testutil/integration/infosync_test.go
  testutil/validatormock/synccomm.go
Labels: merge when ready

#1998 testutil/beaconmock: speed up head producer tests
  testutil/beaconmock/headproducer_internal_test.go
Labels: merge when ready

#2000 keystore: speed up tests
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  dkg/dkg_test.go
  dkg/transport.go
  eth2util/keymanager/keymanager_test.go
  eth2util/keystore/keystore_test.go
  testutil/integration/simnet_test.go
Labels: merge when ready

#2001 cmd/combine: add support for insure keys in tests
  cmd/combine/combine.go
  cmd/combine/combine_test.go
Labels: merge when ready

#1995 app: add beacon node far behind metric value to readyz
  app/metrics.go
  app/monitoringapi.go
  app/monitoringapi_internal_test.go
  testutil/compose/static/grafana/dash_charon_overview.json
Labels: merge when ready

#2006 gomod: upgrade clockwork to v0.4.0
  core/scheduler/scheduler_test.go
  go.mod
  go.sum
Labels: merge when ready

#2008 p2p: increase relay reserver check freq
  p2p/relay.go
Labels: merge when ready

#2009 cmd/relay: increase relay connection limit
  cmd/relay/p2p.go
Labels: merge when ready

#2010 app/forkjoin: fix race in test
  app/forkjoin/forkjoin_test.go
Labels: merge when ready

#2007 dkg: ensure number of commitments
  dkg/dkg.go
  dkg/frostp2p.go
Labels: bug, merge when ready

#2011 dkg: shutdown race workaround
  cmd/dkg.go
  dkg/dkg.go
  dkg/dkg_test.go
Labels: merge when ready

#2012 p2p: add disconnect logs
  p2p/p2p.go
Labels: merge when ready

#2015 p2p: fix relay conn checker
  p2p/relay.go
Labels: merge when ready

#2016 testutil/compose: add build-local command
  testutil/compose/compose/main.go
  testutil/compose/define.go
Labels: merge when ready

#2017 p2p: fix missing connection logs
  p2p/p2p.go
Labels: merge when ready

#2019 version: bump version to v0.16.0-dev
  app/version/version.go
Labels: merge when ready

#2020 github/workflows: include release branch in codeql
  .github/workflows/codeql-analysis.yml
Labels: merge when ready, branch-main

#2018 version: bump version to v0.15.0-rc1
  app/version/version.go
Labels: merge when ready

#2023 github/workflows: remove release branch check
  .github/workflows/build-push-deploy.yml
Labels: merge when ready, branch-release

#2024 github/workflows: improve docker image tagging rules
  .github/workflows/build-push-deploy-promrated.yaml
  .github/workflows/build-push-deploy.yml
Labels: merge when ready, branch-main

#2027 core/tracker: unlock mutex
  core/scheduler/scheduler.go
  core/tracker/incldelay.go
Labels: merge when ready

#2030 core/tracker: unlock mutex
  core/scheduler/scheduler.go
  core/tracker/incldelay.go
Labels: merge when ready

#2035 app/eth2wrap: fix lazy client if http times out
  app/app.go
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/eth2wrap_test.go
  app/eth2wrap/genwrap/genwrap.go
  app/eth2wrap/lazy.go
  core/scheduler/scheduler_test.go
Labels: merge when ready

#2038 app/eth2wrap: fix lazy client if http times out
  app/app.go
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/eth2wrap_test.go
  app/eth2wrap/genwrap/genwrap.go
  app/eth2wrap/lazy.go
  core/scheduler/scheduler_test.go
Labels: merge when ready, branch-release

#2036 testutil/compose: refactor to multiple beacon nodes
  testutil/compose/compose/main.go
  testutil/compose/config.go
  testutil/compose/lock.go
  testutil/compose/testdata/TestDockerCompose_run_template.golden
  testutil/compose/testdata/TestDockerCompose_run_yml.golden
  testutil/compose/testdata/TestNewDefaultConfig.golden
Labels: merge when ready

#2040 core/consensus: stricter checking on ConsensusMsg
  core/consensus/component.go
  core/consensus/component_internal_test.go
Labels: bug, merge when ready

#2047 core/deadliner: fix deadliner flappy test
  core/deadline_test.go
Labels: merge when ready

#2041 github/workflows: add a branch labeler
  .github/workflows/label-pr.yml
Labels: merge when ready

#2029 app: fix peer count bn query to occur every min instead of every 10s
  app/monitoringapi.go
Labels: merge when ready

#2051 app: enable libp2p bandwidth metrics
  app/app.go
  p2p/metrics.go
Labels: merge when ready, branch-release

#2048 app/log: support log color configuration
  app/log/config.go
  app/log/testdata/TestCopyFields_logfmt.golden
  app/log/testdata/TestErrorWrapOther_logfmt.golden
  app/log/testdata/TestErrorWrap_logfmt.golden
  app/log/testdata/TestFilterDefault_logfmt.golden
  app/log/testdata/TestFilterNone_logfmt.golden
  app/log/testdata/TestSentinelStack_logfmt.golden
  app/log/testdata/TestWithContext_logfmt.golden
  app/log/testdata/TestWithTopic_logfmt.golden
  cmd/cmd_internal_test.go
  cmd/run.go
  docs/configuration.md
  go.mod
Labels: merge when ready

#2056 testutil/verifypr: limit PR titles to 60 chars
  testutil/verifypr/verify.go
  testutil/verifypr/verify_internal_test.go
Labels: merge when ready

#2057 workflows: run govulncheck on releases
  .github/workflows/govulncheck.yml
Labels: enhancement, merge when ready

#2058 workflows: update Go to 1.20.3 on v0.15 release branch
  .github/workflows/golangci-lint.yml
  .github/workflows/govulncheck.yml
  .github/workflows/pre-commit.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/track-pr.yml
  .github/workflows/verify-pr.yml
  .golangci.yml
  Dockerfile
  testutil/promrated/Dockerfile
Labels: enhancement, merge when ready, branch-release

#2061 sigagg: validate threshold unique partial signatures
  core/sigagg/sigagg.go
  core/sigagg/sigagg_test.go
Labels: merge when ready

#2062 core/fetcher: dedup aggregate attestations
  core/fetcher/fetcher.go
  core/fetcher/fetcher_test.go
Labels: merge when ready

#2063 core/validatorapi: support ssz encoded request bodies
  .golangci.yml
  core/validatorapi/router.go
  core/validatorapi/router_internal_test.go
  testutil/compose/lock.go
  testutil/compose/testdata/TestDockerCompose_lock_dkg_template.golden
  testutil/compose/testdata/TestDockerCompose_lock_dkg_yml.golden
  testutil/compose/testdata/TestDockerCompose_run_template.golden
  testutil/compose/testdata/TestDockerCompose_run_yml.golden
  testutil/integration/simnet_test.go
  testutil/random.go
Labels: merge when ready

#2064 core/validatorapi: support ssz encoded request bodies
  .golangci.yml
  core/validatorapi/router.go
  core/validatorapi/router_internal_test.go
  testutil/integration/simnet_test.go
  testutil/random.go
Labels: merge when ready, branch-release

#2066 github/workflows: run actions on release branch commits
  .github/workflows/codeql-analysis.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/govulncheck.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
Labels: merge when ready, branch-release

#2072 core/tracker: initialise participation metrics
  core/tracker/tracker.go
Labels: merge when ready

#2074 eth2util: update deposit cli version
  eth2util/deposit/deposit.go
  eth2util/deposit/testdata/TestMarshalDepositData.golden
Labels: merge when ready

#2073 enr: fix duplicate keys in enr parsing
  eth2util/enr/enr.go
  eth2util/enr/enr_test.go
Labels: merge when ready

#2075 core/tracker: add missed participation counter
  core/tracker/metrics.go
  core/tracker/tracker.go
Labels: merge when ready

#2032 github/workflows: add deploy relay workflows
  .github/workflows/build-push-deploy.yml
  .github/workflows/deploy-relay-dev.yml
  .github/workflows/deploy-relay-prod.yml
Labels: merge when ready

#2082 github/workflows: fix multi line formatting
  .github/workflows/build-push-deploy.yml
  .github/workflows/deploy-relay-dev.yml
  .github/workflows/deploy-relay-prod.yml
Labels: merge when ready

#2084 core/tracker: ensure success/fail/expected counters
  core/tracker/metrics.go
  core/tracker/tracker.go
Labels: merge when ready, branch-release

#2079 core/consensus: verify wire justification duties
  core/consensus/component.go
  core/consensus/component_internal_test.go
Labels: bug, merge when ready, sigp audit

#2086 core/tracker: improve ignoring of unsupported duties
  core/tracker/tracker.go
  core/tracker/tracker_internal_test.go
  testutil/random.go
Labels: merge when ready

#2087 core/tracker: improve ignoring of unsupported duties
  core/tracker/tracker.go
  core/tracker/tracker_internal_test.go
  testutil/random.go
Labels: merge when ready, branch-release

#2088 dkg: add nil checks
  dkg/frostp2p.go
Labels: merge when ready, sigp audit

#2081 rlp: fix bug in decodeLength
  eth2util/rlp/rlp.go
  eth2util/rlp/rlp_internal_test.go
Labels: merge when ready

#2089 beaconmock: remove backoff dependency
  go.mod
  testutil/beaconmock/headproducer_internal_test.go
Labels: merge when ready, sigp audit

#2091 tbls: remove legacy Kryptology-based code
  app/app.go
  cluster/distvalidator.go
  cluster/helpers.go
  cluster/helpers_internal_test.go
  cluster/lock.go
  cluster/test_cluster.go
  cmd/combine/combine.go
  cmd/combine/combine_test.go
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  core/consensus/component_test.go
  core/eth2signeddata.go
  core/eth2signeddata_test.go
  core/parsigex/parsigex.go
  core/parsigex/parsigex_test.go
  core/sigagg/sigagg.go
  core/sigagg/sigagg_test.go
  core/validatorapi/router.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_internal_test.go
  core/validatorapi/validatorapi_test.go
  dkg/disk.go
  dkg/dkg.go
  dkg/dkg_internal_test.go
  dkg/dkg_test.go
  dkg/frost.go
  dkg/keycast.go
  eth2util/deposit/deposit.go
  eth2util/deposit/deposit_test.go
  eth2util/eth2exp/attagg_test.go
  eth2util/keymanager/keymanager_test.go
  eth2util/keystore/keystore.go
  eth2util/keystore/keystore_test.go
  eth2util/signing/signing.go
  eth2util/signing/signing_test.go
  p2p/peer_test.go
  tbls/herumi.go
  tbls/kryptology.go
  tbls/tbls.go
  tbls/tbls_test.go
  tbls/tblsconv/tblsconv.go
  tbls/tblsconv/tblsconv_test.go
  tbls/tss.go
  tbls/tss_internal_test.go
  tbls/tss_test.go
  tbls/v2/tblsconv/tblsconv.go
  tbls/v2/tblsconv/tblsconv_test.go
  testutil/integration/helpers_test.go
  testutil/integration/simnet_test.go
  testutil/random.go
  testutil/validatormock/validatormock.go
Labels: merge when ready, refactor

#2090 core: add nil checks
  core/parsigex/parsigex.go
  core/priority/component.go
  core/proto.go
  core/proto_test.go
Labels: merge when ready

#2095 compose: update compose dashboard
  app/monitoringapi_internal_test.go
  testutil/beaconmock/options.go
  testutil/compose/static/grafana/dash_charon_overview.json
Labels: merge when ready

#2100 tbls: remove kryptology implementation
  app/app.go
  app/featureset/featureset.go
  cluster/helpers_internal_test.go
  cmd/combine/combine_test.go
  cmd/createcluster_internal_test.go
  core/consensus/component_test.go
  core/eth2signeddata_test.go
  core/parsigex/parsigex_test.go
  core/sigagg/sigagg_test.go
  core/validatorapi/validatorapi_test.go
  dkg/dkg_test.go
  eth2util/signing/signing_test.go
  p2p/peer_test.go
  tbls/kryptology.go
  tbls/tbls.go
  tbls/tbls_test.go
  testutil/integration/helpers_test.go
Labels: merge when ready, refactor

#2102 app/version: fix main branch version
  app/version/version.go
Labels: merge when ready

#2096 core/consensus: double lead time alpha feature
  app/app.go
  app/featureset/featureset.go
  core/consensus/component.go
  core/consensus/component_test.go
  core/consensus/roundtimer.go
  core/consensus/roundtimer_internal_test.go
  core/consensus/sniffed_internal_test.go
Labels: merge when ready

#2108 *: update licence
  LICENSE
Labels: merge when ready

#2110 core/consensus: implement simulator test
  app/forkjoin/forkjoin.go
  core/consensus/strategysim_internal_test.go
Labels: merge when ready

#2105 testutil/beaconmock: fix fuzz issues
  app/app.go
  core/scheduler/scheduler.go
  core/tracker/incldelay.go
  core/validatorapi/validatorapi.go
  testutil/beaconmock/beaconmock_fuzz.go
  testutil/compose/fuzz/beacon_fuzz_test.go
Labels: merge when ready

#2107 dkg: verify valIdx in frost dkg messages
  dkg/dkg.go
  dkg/frostp2p.go
  dkg/frostp2p_internal_test.go
Labels: merge when ready

#2113 core/consensus: speed up simulator
  core/consensus/strategysim_internal_test.go
Labels: merge when ready

#2119 compose/smoke: add vouch in smoke tests
  testutil/compose/smoke/smoke_test.go
  testutil/compose/static/vouch/Dockerfile
Labels: merge when ready

#2112 core/tracker: improve participation
  core/tracker/tracker.go
  core/tracker/tracker_internal_test.go
Labels: merge when ready

#2115 qbft: validate message type
  core/consensus/component.go
  core/consensus/component_internal_test.go
  core/consensus/msg_internal_test.go
Labels: merge when ready

#2116 core/consensus: improve simulator test
  app/log/config.go
  core/consensus/strategysim_internal_test.go
Labels: merge when ready

#2120 core/tracker: refactor inclusion checker
  .golangci.yml
  app/app.go
  app/eth2wrap/synthproposer.go
  app/monitoringapi.go
  app/privkeylock/privkeylock.go
  cluster/definition.go
  core/tracker/incldelay.go
  core/tracker/incldelay_internal_test.go
  core/tracker/inclusion.go
  core/tracker/inclusion_internal_test.go
  core/tracker/metrics.go
  core/tracking.go
  testutil/verifypr/verify.go
Labels: merge when ready

#2124 core/tracker: check aggbits for inclusion
  app/app.go
  core/fetcher/fetcher_test.go
  core/interfaces.go
  core/tracker/inclusion.go
  core/tracker/inclusion_internal_test.go
  core/tracking.go
  testutil/random.go
Labels: merge when ready

#2121 app/eth2wrap: implement and wire validator cache
  app/app.go
  app/disk_internal_test.go
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/genwrap/genwrap.go
  app/eth2wrap/httpwrap.go
  app/eth2wrap/lazy.go
  app/eth2wrap/synthproposer.go
  app/eth2wrap/synthproposer_test.go
  app/eth2wrap/valcache.go
  app/eth2wrap/valcache_test.go
  app/vmock.go
  core/scheduler/scheduler.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_test.go
  testutil/beaconmock/beaconmock.go
  testutil/beaconmock/options.go
  testutil/validatormock/attest.go
  testutil/validatormock/synccomm.go
  testutil/validatormock/validatormock.go
  testutil/validatormock/validatormock_test.go
Labels: merge when ready

#2129 core/consensus: refactor alpha timer AB testing
  app/app.go
  app/featureset/featureset.go
  core/consensus/component.go
  core/consensus/component_test.go
  core/consensus/metrics.go
  core/consensus/roundtimer.go
  core/consensus/roundtimer_internal_test.go
  core/consensus/strategysim_internal_test.go
Labels: merge when ready

#2123 core/sigagg: verify aggregated signature
  app/app.go
  core/sigagg/sigagg.go
  core/sigagg/sigagg_test.go
  core/signeddata.go
Labels: merge when ready

#2133 core/consensus: include timer type in logs
  core/consensus/component.go
Labels: merge when ready

#2135 app: fix flapping test
  app/monitoringapi_internal_test.go
Labels: merge when ready

#2139 core/qbft: add support for lazy input values
  core/consensus/component.go
  core/consensus/sniffed_internal_test.go
  core/consensus/strategysim_internal_test.go
  core/qbft/qbft.go
  core/qbft/qbft_internal_test.go
Labels: merge when ready

#2127 app/privkeylock: add periodic updates and timestamps
  app/app.go
  app/lifecycle/order.go
  app/lifecycle/orderstart_string.go
  app/lifecycle/orderstop_string.go
  app/privkeylock/privkeylock.go
  app/privkeylock/privkeylock_internal_test.go
  app/privkeylock/privkeylock_test.go
  dkg/dkg.go
  main.go
Labels: merge when ready

#2140 core/consensus: add support for eager consensus
  core/consensus/component.go
  core/consensus/component_internal_test.go
  core/consensus/roundtimer.go
  core/consensus/transport.go
  core/interfaces.go
  core/leadercast/leadercast.go
  core/retry.go
  core/tracing.go
  core/tracking.go
Labels: merge when ready

#2143 precommit: lint importing of testutil
  .pre-commit-config.yaml
  .pre-commit/run_testutil.sh
  app/app.go
  app/vmock.go
  tools.go
Labels: merge when ready

#2144 core/qbft: fix lazy value issue
  core/qbft/qbft.go
  core/qbft/qbft_internal_test.go
Labels: merge when ready
