Repository ObolNetwork/charon, pull requests merged in 2023-05, with the labels that each got.

#2136 createdkg: validate inputs
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  cmd/createdkg.go
  cmd/createdkg_internal_test.go
  testutil/compose/define.go
  testutil/compose/lock.go
  testutil/compose/testdata/TestDockerCompose_define_dkg_template.golden
  testutil/compose/testdata/TestDockerCompose_define_dkg_yml.golden
  testutil/compose/testdata/TestDockerCompose_lock_create_template.golden
  testutil/compose/testdata/TestDockerCompose_lock_create_yml.golden
Labels: merge when ready, sigp audit

#2162 app/log: support logger instances via ctx
  app/log/config.go
  app/log/log.go
  app/log/log_test.go
  app/log/testdata/TestCopyFields_json.golden
  app/log/testdata/TestCopyFields_logfmt.golden
  app/log/testdata/TestErrorWrapOther_console.golden
  app/log/testdata/TestErrorWrapOther_json.golden
  app/log/testdata/TestErrorWrapOther_logfmt.golden
  app/log/testdata/TestErrorWrap_console.golden
  app/log/testdata/TestErrorWrap_json.golden
  app/log/testdata/TestErrorWrap_logfmt.golden
  app/log/testdata/TestFilterDefault_json.golden
  app/log/testdata/TestFilterDefault_logfmt.golden
  app/log/testdata/TestFilterNone_json.golden
  app/log/testdata/TestFilterNone_logfmt.golden
  app/log/testdata/TestInstance.golden
  app/log/testdata/TestSentinelStack_console.golden
  app/log/testdata/TestSentinelStack_json.golden
  app/log/testdata/TestSentinelStack_logfmt.golden
  app/log/testdata/TestWithContext_json.golden
  app/log/testdata/TestWithContext_logfmt.golden
  app/log/testdata/TestWithTopic_json.golden
  app/log/testdata/TestWithTopic_logfmt.golden
Labels: merge when ready

#2163 core/consensus: improve simulator
  core/consensus/strategysim_internal_test.go
Labels: merge when ready

#2168 core/tracker: add inclusion missed debug logs
  core/tracker/inclusion.go
Labels: merge when ready

#2167 eth2util/keystore: order keystores by index
  cmd/combine/combine.go
  cmd/combine/combine_test.go
  eth2util/keystore/keystore.go
  eth2util/keystore/keystore_internal_test.go
  eth2util/keystore/keystore_test.go
Labels: bug, merge when ready

#2174 eth2util/signing: add constant genesis domain test
  eth2util/signing/signing_test.go
  testutil/beaconmock/beaconmock.go
  testutil/beaconmock/options.go
Labels: merge when ready

#2178 cmd: improve error logs
  app/app.go
  cmd/cmd.go
  cmd/combine/combine.go
  cmd/create.go
  cmd/createdkg.go
  cmd/run.go
  dkg/dkg.go
  main.go
Labels: merge when ready

#2177 core/fetcher: remove inconsistent att data metrics
  core/fetcher/fetcher.go
  core/fetcher/metrics.go
Labels: merge when ready

#2179 eth2util/keystore: concurrently read/write keystore files
  eth2util/keystore/keystore.go
Labels: enhancement, merge when ready

#2185 app/genssz: support transform funcs
  app/genssz/genssz.go
  app/genssz/template.go
  app/genssz/testdata/example.go
  app/genssz/testdata/ssz_gen.go
  app/genssz/types.go
Labels: merge when ready

#2186 cmd/relay: properly skip test on bind issue
  cmd/relay/relay_internal_test.go
  core/consensus/component_test.go
Labels: merge when ready

#2187 cluster/state: implement load and materialise
  cluster/state/load.go
  cluster/state/materialise.go
  cluster/state/mutation.go
  cluster/state/mutationlegacylock.go
  cluster/state/mutationlegacylock_test.go
  cluster/state/types.go
Labels: merge when ready

#2190 app: refactor to use cluster state
  app/app.go
  app/disk.go
  app/disk_internal_test.go
  cluster/state/cluster.go
  cluster/state/helpers.go
  cluster/state/load.go
  cluster/state/load_test.go
  cluster/state/materialise.go
  cluster/state/mutationlegacylock.go
  cluster/state/mutationlegacylock_test.go
  cluster/state/ssz_gen.go
  cluster/state/testdata/TestLegacyLock_cluster.golden
  cluster/state/testdata/TestLegacyLock_json.golden
  cluster/state/types.go
Labels: merge when ready

#2173 *: cron job for long wait dkg
  .github/workflows/long-wait-dkg.yml
  app/privkeylock/privkeylock.go
  testutil/integration/longwait_dkg_test.go
Labels: merge when ready

#2181 *: misc audit fixes
  dkg/keycast.go
  docs/structure.md
  p2p/peer.go
Labels: merge when ready

#2192 tbls: support deterministic key gen for testing
  cluster/test_cluster.go
  tbls/herumi.go
  tbls/tbls.go
  tbls/tbls_test.go
Labels: merge when ready

#2193 cluster/state: add node approvals
  cluster/state/helpers.go
  cluster/state/mutation.go
  cluster/state/mutationnodeapproval.go
  cluster/state/mutationnodeapproval_test.go
  cluster/state/ssz_gen.go
  cluster/state/testdata/TestLegacyLock_json.golden
  cluster/state/testdata/TestNodeApprovals_json.golden
  cluster/state/types.go
Labels: merge when ready

#2195 app/genssz: transforms for composite list types
  app/genssz/template.go
  app/genssz/testdata/example.go
  app/genssz/testdata/ssz_gen.go
Labels: merge when ready

#2150 github/workflows: add relay-2 to deploy action
  .github/workflows/deploy-relay-prod.yml
Labels: merge when ready

#2191 core/validatorapi: get all validators
  core/validatorapi/router.go
  core/validatorapi/router_internal_test.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_test.go
  testutil/beaconmock/options.go
  testutil/random.go
Labels: merge when ready

#2197 cluster/state: add validators mutation type
  cluster/state/cluster.go
  cluster/state/mutation.go
  cluster/state/mutationaddvalidator.go
  cluster/state/mutationaddvalidator_test.go
  cluster/state/ssz_gen.go
  cluster/state/testdata/TestAddValidators_json.golden
  cluster/state/testdata/TestLegacyLock_cluster.golden
  cluster/state/testdata/lock2.json
Labels: merge when ready

#2198 core/scheduler: verify duty pubkeys in resolveDuties
  core/scheduler/scheduler.go
  core/scheduler/scheduler_internal_test.go
Labels: merge when ready

#2126 app: refactor lockfile fork version mismatch error
  app/app.go
  core/dutydb/memory.go
Labels: merge when ready

#2199 cluster/state: implement composite add validators
  cluster/state/cluster.go
  cluster/state/helpers.go
  cluster/state/mutation.go
  cluster/state/mutationaddvalidator.go
  cluster/state/mutationaddvalidator_test.go
  cluster/state/ssz_gen.go
  cluster/state/testdata/TestAddValidators_json.golden
  cluster/state/testdata/TestGenValidators_json.golden
Labels: merge when ready

#2202 dkg: pre-generate validator registration messages
  app/featureset/featureset.go
  cmd/dkg.go
  dkg/dkg.go
  dkg/dkg_test.go
  dkg/exchanger.go
  eth2util/registration/registration.go
  eth2util/registration/registration_test.go
Labels: enhancement, merge when ready

#2206 eth2util/keystore: finite amount of goroutines in read/write
  dkg/dkg_test.go
  eth2util/keystore/keystore.go
Labels: merge when ready

#2207 testutil/integration: add DKG test with 5000 validators
  .github/workflows/nightly-dkg.yml
  cmd/dkg.go
  dkg/dkg.go
  dkg/dkg_test.go
  testutil/integration/nightly_dkg_test.go
Labels: merge when ready

#2212 p2p: enable delimited protocol negotiation
  p2p/receive_test.go
  p2p/sender.go
Labels: merge when ready

#2208 cmd: generate validator builder registrations
  cluster/examples/cluster-definition-004.json
  cluster/version.go
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  dkg/dkg.go
  dkg/dkg_test.go
  eth2util/registration/registration.go
Labels: merge when ready

#2213 core/consensus: change round AB test timers
  core/consensus/roundtimer.go
  core/consensus/roundtimer_internal_test.go
Labels: merge when ready

#2214 cluster/state: support for builder registrations
  cluster/cluster_internal_test.go
  cluster/state/cluster.go
  cluster/state/mutation.go
  cluster/state/mutationaddvalidator_test.go
  cluster/state/mutationlegacylock.go
  cluster/state/ssz_gen.go
  cluster/state/testdata/TestAddValidators_json.golden
  cluster/state/testdata/TestGenValidators_json.golden
  cluster/state/testdata/TestLegacyLock_cluster.golden
  cluster/state/testdata/TestLegacyLock_json.golden
  cluster/state/testdata/TestNodeApprovals_json.golden
  cluster/state/testdata/lock.json
  cluster/state/types.go
  cluster/test_cluster.go
Labels: merge when ready

#2218 core/consensus: add 2 of 3 test
  core/consensus/component_test.go
  core/qbft/qbft_internal_test.go
Labels: merge when ready

#2215 docs: add metrics reference
  app/promauto/promauto.go
  cmd/cmd_internal_test.go
  cmd/markdown_internal_test.go
  docs/README.md
  docs/metrics.md
Labels: merge when ready

#2222 p2p: force direct connections
  app/app.go
  app/lifecycle/order.go
  app/lifecycle/orderstart_string.go
  cmd/relay/p2p.go
  p2p/p2p.go
Labels: merge when ready

#2225 *: increase test timeout
  .github/workflows/build-push-deploy-promrated.yaml
  .github/workflows/build-push-deploy.yml
  .github/workflows/nightly-dkg.yml
  .github/workflows/nightly-tests.yml
  testutil/integration/nightly_dkg_test.go
Labels: merge when ready

#2219 core/bcast: add pre-generate registrations
  app/app.go
  app/app_internal_test.go
  cluster/cluster_test.go
  cluster/state/testdata/TestAddValidators_json.golden
  cluster/test_cluster.go
  cluster/testdata/cluster_lock_v1_7_0.json
  cmd/createcluster.go
  core/bcast/metrics.go
  core/bcast/recast.go
  dkg/dkg.go
  dkg/dkg_test.go
  docs/metrics.md
  eth2util/network.go
  eth2util/registration/registration.go
Labels: merge when ready

#2230 p2p: use direct connection for ping
  p2p/p2p.go
  p2p/ping.go
Labels: merge when ready

#2224 dkg: lock hash k1 signature in lock file
  cluster/cluster_test.go
  cluster/distvalidator.go
  cluster/lock.go
  cluster/state/testdata/TestLegacyLock_json.golden
  cluster/testdata/cluster_lock_v1_7_0.json
  dkg/bcast/impl.go
  dkg/bcast/impl_test.go
  dkg/bcast/server.go
  dkg/dkg.go
  dkg/dkgpb/v1/nodesigs.pb.go
  dkg/dkgpb/v1/nodesigs.proto
  dkg/frostp2p.go
  dkg/nodesigs.go
Labels: merge when ready

#2232 github: overwrite version with tagged releases
  .github/workflows/build-push-deploy.yml
  Dockerfile
  app/version/version.go
Labels: merge when ready

#2233 github: tag image with branch version
  .github/workflows/build-push-deploy.yml
Labels: merge when ready

#2236 app/version: fix minor func
  app/version/version.go
  app/version/version_test.go
  core/tracker/inclusion.go
Labels: merge when ready

#2234 cluster: correct ssz hash calculation
  cluster/ssz.go
  cluster/state/testdata/TestGenValidators_json.golden
  cluster/state/testdata/TestLegacyLock_cluster.golden
  cluster/state/testdata/TestLegacyLock_json.golden
  cluster/state/testdata/lock.json
  cluster/testdata/cluster_lock_v1_7_0.json
Labels: merge when ready

#2237 cmd: reduce minimum nodes to 3
  cmd/createcluster.go
  cmd/createdkg.go
  cmd/createdkg_internal_test.go
  cmd/testdata/TestCreateCluster_goerli_files.golden
  cmd/testdata/TestCreateCluster_goerli_output.golden
  testutil/compose/smoke/smoke_test.go
Labels: merge when ready

#2242 core/tracker: instrument structured reasons
  core/tracker/metrics.go
  core/tracker/reason.go
  core/tracker/tracker.go
  core/tracker/tracker_internal_test.go
  docs/metrics.md
Labels: merge when ready

#2243 cluster: verify registrations
  cluster/definition.go
  cluster/lock.go
  cluster/state/testdata/TestAddValidators_json.golden
  cluster/state/testdata/TestNodeApprovals_json.golden
  cluster/test_cluster.go
Labels: merge when ready

#2244 eth2util: remove ropsten from supported networks
  eth2util/network.go
  eth2util/network_test.go
Labels: merge when ready

#2248 cmd: auto-generate failure reason doc
  cmd/markdown_internal_test.go
  core/tracker/reason.go
  docs/reasons.md
Labels: merge when ready

#2247 cluster: move v1.7.0 to draft
  cluster/version.go
  cmd/createcluster_internal_test.go
  dkg/dkg_test.go
Labels: merge when ready

#2249 core/consensus: propose returns instance errors
  core/consensus/component.go
Labels: merge when ready

#2238 app: support vmock registrations per epoch
  app/app.go
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/genwrap/genwrap.go
  app/eth2wrap/httpwrap.go
  app/eth2wrap/lazy.go
  app/vmock.go
  core/validatorapi/router.go
  core/validatorapi/teku.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_test.go
  eth2util/eth2exp/proposeconf.go
  testutil/beaconmock/beaconmock.go
  testutil/beaconmock/options.go
  testutil/integration/simnet_test.go
  testutil/validatormock/validatormock.go
Labels: merge when ready

#2251 core/scheduler: fix race
  core/scheduler/scheduler.go
Labels: merge when ready

#2250 cmd: add NodeSignatures to create cluster
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
Labels: merge when ready

#2252 doc: improve go guidelines
  docs/README.md
  docs/goguidelines.md
Labels: merge when ready
