Repository ObolNetwork/charon, pull requests merged in 2023-02, with the labels that each got.

#1731 core/infosync: prioritise proposal types
  app/app.go
  app/app_test.go
  core/infosync/infosync.go
  core/types.go
Labels: merge when ready

#1745 featureset: `herumi_bls` feature flag
  .github/workflows/test.yml
  app/app.go
  app/featureset/featureset.go
  testutil/compose/define.go
Labels: enhancement, merge when ready

#1749 testutil/compose: build local container
  .github/workflows/test.yml
  testutil/compose/compose/main.go
  testutil/compose/config.go
  testutil/compose/define.go
  testutil/compose/docker-compose.template
  testutil/compose/lock.go
  testutil/compose/run.go
  testutil/compose/smoke/smoke_test.go
  testutil/compose/testdata/TestDockerCompose_define_dkg_template.golden
  testutil/compose/testdata/TestDockerCompose_define_dkg_yml.golden
  testutil/compose/testdata/TestDockerCompose_lock_create_template.golden
  testutil/compose/testdata/TestDockerCompose_lock_create_yml.golden
  testutil/compose/testdata/TestDockerCompose_lock_dkg_template.golden
  testutil/compose/testdata/TestDockerCompose_lock_dkg_yml.golden
  testutil/compose/testdata/TestDockerCompose_run_template.golden
  testutil/compose/testdata/TestDockerCompose_run_yml.golden
  testutil/compose/testdata/TestNewDefaultConfig.golden
Labels: merge when ready

#1735 workflows: update issue template
  .github/ISSUE_TEMPLATE/feature_flag.md
  .github/ISSUE_TEMPLATE/feature_ticket.md
Labels: merge when ready

#1755 cmd: validator all withdrawal addresses
  app/app.go
  cluster/definition.go
  cmd/createcluster.go
  dkg/dkg.go
Labels: merge when ready

#1740 testutil/promrated: add network statistics reporting to promrated for each network
  testutil/promrated/metrics.go
  testutil/promrated/promrated.go
  testutil/promrated/rated.go
  testutil/promrated/rated_internal_test.go
  testutil/promrated/testdata/TestGetNetworkStatistics.golden
  testutil/promrated/testdata/TestGetValidatorStatistics.golden
Labels: merge when ready

#1751 core: introduce mutable builder enabled config
  app/app.go
  app/priorities.go
  core/config.go
  core/scheduler/scheduler.go
  core/scheduler/scheduler_test.go
  core/validatorapi/teku.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_internal_test.go
  core/validatorapi/validatorapi_test.go
  testutil/helpers.go
Labels: merge when ready

#1754 core/sigagg: refactor to use tbls/v2
  core/sigagg/sigagg.go
  core/sigagg/sigagg_test.go
  tbls/v2/tblsconv/tblsconv.go
Labels: merge when ready, refactor

#1706 tracker/tracker2: add tests and featureflag
  app/app.go
  app/featureset/featureset.go
  core/interfaces.go
  core/tracker/tracker2/tracker.go
  core/tracker/tracker2/tracker_internal_test.go
  core/tracking.go
Labels: merge when ready

#1760 app/eth2wrap: add lazy init
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/eth2wrap_test.go
  app/eth2wrap/genwrap/genwrap.go
  app/eth2wrap/httpwrap.go
  app/eth2wrap/lazy.go
  app/eth2wrap/synthproposer.go
Labels: merge when ready

#1762 app: disable mutable builderAPI config
  app/priorities.go
Labels: merge when ready

#1761 app: refactor VC readyz checks
  app/app.go
  app/metrics.go
  app/monitoringapi.go
  app/monitoringapi_internal_test.go
Labels: merge when ready

#1763 tbls/v2: implement FastAggregateVerify and CombineSignatures methods
  tbls/v2/herumi/herumi.go
  tbls/v2/kryptology/kryptology.go
  tbls/v2/tbls.go
  tbls/v2/tbls_test.go
  tbls/v2/unimplemented.go
Labels: enhancement, merge when ready

#1766 ethu2util/signing: refactor to use tbls/v2
  core/eth2signeddata.go
  core/eth2signeddata_test.go
  core/parsigex/parsigex_test.go
  core/validatorapi/validatorapi_test.go
  eth2util/signing/signing.go
  eth2util/signing/signing_test.go
Labels: merge when ready, refactor

#1765 validatorapi: add node version
  core/validatorapi/eth2types.go
  core/validatorapi/router.go
  core/validatorapi/router_internal_test.go
  core/validatorapi/validatorapi.go
Labels: merge when ready

#1768 cluster: refactor to use tbls/v2
  app/app_test.go
  cluster/cluster_test.go
  cluster/helpers.go
  cluster/helpers_internal_test.go
  cluster/lock.go
  cluster/test_cluster.go
  cmd/createcluster_internal_test.go
  core/consensus/component_test.go
  dkg/dkg_test.go
  p2p/peer_test.go
  tbls/v2/tblsconv/tblsconv.go
  testutil/combine/main_internal_test.go
Labels: merge when ready, refactor

#1770 app: initialize tbls/v2 earlier
  app/app.go
Labels: merge when ready

#1771 tbls/v2: move implementation to the root level of v2
  app/app.go
  app/app_test.go
  cluster/helpers_internal_test.go
  cmd/createcluster_internal_test.go
  core/consensus/component_test.go
  core/eth2signeddata_test.go
  core/parsigex/parsigex_test.go
  core/sigagg/sigagg_test.go
  core/validatorapi/validatorapi_test.go
  dkg/dkg_test.go
  eth2util/signing/signing_test.go
  p2p/peer_test.go
  tbls/v2/herumi.go
  tbls/v2/kryptology.go
  tbls/v2/tbls.go
  tbls/v2/tbls_test.go
  tbls/v2/unimplemented.go
  testutil/combine/main_internal_test.go
  testutil/compose/smoke/smoke_test.go
Labels: merge when ready, refactor

#1767 validatorapi: refactor tests
  core/validatorapi/router_internal_test.go
Labels: merge when ready

#1774 dkg: refactor to use tbls/v2
  dkg/disk.go
  dkg/dkg.go
  dkg/dkg_internal_test.go
  dkg/dkg_test.go
  dkg/frost.go
  dkg/keycast.go
  dkg/keycast_internal_test.go
  tbls/v2/tblsconv/tblsconv.go
Labels: merge when ready, refactor

#1783 eth2util/enr: add backwards compatibility with older versions
  eth2util/enr/enr.go
  eth2util/enr/enr_internal_test.go
  testutil/random.go
Labels: merge when ready

#1785 app/eth2wrap: select best client
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/eth2wrap_test.go
  app/eth2wrap/genwrap/genwrap.go
Labels: merge when ready

#1784 eth2util: refactor to use tbls/v2
  app/app.go
  app/simnet_test.go
  cluster/helpers.go
  cluster/test_cluster.go
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  core/eth2signeddata.go
  core/eth2signeddata_test.go
  core/parsigex/parsigex.go
  core/parsigex/parsigex_test.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_internal_test.go
  core/validatorapi/validatorapi_test.go
  dkg/disk.go
  dkg/dkg_test.go
  eth2util/deposit/deposit.go
  eth2util/deposit/deposit_test.go
  eth2util/keymanager/keymanager_test.go
  eth2util/keystore/keystore.go
  eth2util/keystore/keystore_test.go
  eth2util/signing/signing.go
  eth2util/signing/signing_test.go
  testutil/combine/main.go
  testutil/combine/main_internal_test.go
  testutil/validatormock/validatormock.go
Labels: merge when ready, refactor

#1789 charon: refactor the remaining Kryptology and tbls pieces
  app/app.go
  cluster/distvalidator.go
  core/consensus/msg_internal_test.go
  core/consensus/testdata/TestHashProto.golden
  core/validatorapi/router.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_internal_test.go
  eth2util/eth2exp/attagg_test.go
  eth2util/keymanager/keymanager_test.go
  tbls/v2/tblsconv/tblsconv.go
  testutil/combine/main.go
  testutil/random.go
Labels: merge when ready, refactor

#1791 p2p: adds debug logs for metric issue
  p2p/p2p.go
Labels: merge when ready

#1792 p2p: improve debug logs
  p2p/p2p.go
Labels: merge when ready

#1793 tbls/v2: add tests to tblsconv, small refactors
  core/sigagg/sigagg.go
  core/sigagg/sigagg_test.go
  eth2util/eth2exp/attagg_test.go
  tbls/v2/tblsconv/tblsconv.go
  tbls/v2/tblsconv/tblsconv_test.go
Labels: merge when ready, refactor

#1798 p2p: fix connection metrics
  p2p/p2p.go
Labels: merge when ready

#1800 cmd: remove deprecated bootnode command
  cmd/cmd.go
  cmd/relay.go
Labels: merge when ready

#1802 cmd: rescope distributed validator pubkey during slice iteration
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
Labels: bug, merge when ready

#1801 cmd: remove deprecated data-dir flag
  cmd/run.go
  cmd/run_internal_test.go
  docs/configuration.md
Labels: merge when ready

#1803 validatorapi: fix content type in http response
  core/validatorapi/router.go
  core/validatorapi/router_internal_test.go
Labels: merge when ready

#1797 compose: fix very large smoke test
  app/app.go
  app/vmock.go
  cmd/cmd_internal_test.go
  cmd/run.go
  core/scheduler/testdata/TestSchedulerDuties_grouped.golden
  core/scheduler/testdata/TestSchedulerDuties_spread.golden
  core/scheduler/testdata/TestSchedulerDuties_spread_errors.golden
  core/validatorapi/validatorapi_test.go
  docs/configuration.md
  testutil/beaconmock/beaconmock.go
  testutil/beaconmock/options.go
  testutil/beaconmock/testdata/TestDeterministicAttesterDuties.golden
  testutil/beaconmock/testdata/TestDeterministicProposerDuties.golden
  testutil/compose/compose/main.go
  testutil/compose/config.go
  testutil/compose/lock.go
  testutil/compose/new_test.go
  testutil/compose/smoke/smoke_test.go
  testutil/compose/testdata/TestDockerCompose_run_template.golden
  testutil/compose/testdata/TestDockerCompose_run_yml.golden
  testutil/compose/testdata/TestNewDefaultConfig.golden
  testutil/random.go
  testutil/validatormock/testdata/TestAttest_0_aggregations.golden
  testutil/validatormock/testdata/TestAttest_0_attestations.golden
  testutil/validatormock/testdata/TestAttest_1_aggregations.golden
  testutil/validatormock/testdata/TestAttest_1_attestations.golden
  testutil/validatormock/validatormock.go
  testutil/validatormock/validatormock_test.go
Labels: merge when ready

#1805 cmd/relay: fix connection limits
  app/app_test.go
  cmd/relay/p2p.go
Labels: merge when ready

#1809 cmd/relay: fix relay connection limit issue
  cmd/relay/p2p.go
Labels: merge when ready

#1808 app: add a test for remote relay connections
  app/app_test.go
  cmd/relay/p2p.go
Labels: merge when ready

#1816 p2p: remove pointless "No connections to relay" log line
  p2p/relay.go
Labels: merge when ready, refactor

#1815 dkg: add deposit data to lock file
  cmd/createcluster.go
  dkg/disk.go
  dkg/dkg.go
  dkg/dkg_internal_test.go
  dkg/dkg_test.go
  eth2util/deposit/deposit.go
  eth2util/deposit/deposit_test.go
  tbls/v2/tblsconv/tblsconv.go
  tbls/v2/tblsconv/tblsconv_test.go
  testutil/random.go
Labels: merge when ready

#1823 gomod: upgrade libp2p
  app/app_test.go
  core/priority/prioritiser_test.go
  go.mod
  go.sum
  p2p/errors_internal_test.go
  p2p/sender.go
Labels: merge when ready

#1824 *: upgrade to go1.20.1
  .github/workflows/golangci-lint.yml
  .github/workflows/govulncheck.yml
  .github/workflows/pre-commit.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/track-pr.yml
  .github/workflows/verify-pr.yml
  .golangci.yml
  .pre-commit-config.yaml
  Dockerfile
  app/app.go
  app/retry/retry.go
  app/retry/retry_test.go
  cluster/cluster_test.go
  cluster/ssz.go
  cluster/test_cluster.go
  core/consensus/msg_internal_test.go
  dkg/dkg_test.go
  dkg/keycast_internal_test.go
  dkg/sync/sync_test.go
  eth2util/enr/enr_test.go
  go.mod
  p2p/peer_test.go
  testutil/compose/compose_internal_test.go
  testutil/compose/testdata/TestDockerCompose_define_dkg_template.golden
  testutil/compose/testdata/TestDockerCompose_define_dkg_yml.golden
  testutil/promrated/Dockerfile
  testutil/random.go
Labels: merge when ready

#1827 p2p: fix recursive context leak
  p2p/relay.go
Labels: merge when ready

#1830 core: fix duty expired context tracker2
  core/interfaces.go
  core/tracker/tracker2/tracker.go
  core/tracker/tracker2/tracker_internal_test.go
  core/tracking.go
Labels: merge when ready

#1825 app: add beacon node version metric
  app/metrics.go
  app/monitoringapi.go
  testutil/compose/static/grafana/dash_charon_overview.json
Labels: merge when ready

#1799 cmd: add `combine` command
  cmd/cmd.go
  cmd/combine.go
  combine/combine.go
  combine/combine_test.go
  testutil/combine/main.go
  testutil/combine/main_internal_test.go
Labels: enhancement, merge when ready

#1814 compose: add vouch to compose
  app/app.go
  go.mod
  testutil/beaconmock/headproducer.go
  testutil/beaconmock/headproducer_test.go
  testutil/beaconmock/server.go
  testutil/compose/config.go
  testutil/compose/run.go
  testutil/compose/static/vouch/Dockerfile
  testutil/compose/static/vouch/run.sh
  testutil/compose/static/vouch/vouch.yml
  testutil/random.go
Labels: merge when ready

#1832 cmd: add support for multiple addresses via cli
  cluster/cluster_internal_test.go
  cluster/cluster_test.go
  cluster/definition.go
  cluster/ssz.go
  cluster/test_cluster.go
  cluster/testdata/cluster_definition_v1_0_0.json
  cluster/testdata/cluster_definition_v1_1_0.json
  cluster/testdata/cluster_definition_v1_2_0.json
  cluster/testdata/cluster_definition_v1_3_0.json
  cluster/testdata/cluster_definition_v1_4_0.json
  cluster/testdata/cluster_definition_v1_5_0.json
  cluster/testdata/cluster_definition_v1_6_0.json
  cluster/testdata/cluster_lock_v1_0_0.json
  cluster/testdata/cluster_lock_v1_1_0.json
  cluster/testdata/cluster_lock_v1_2_0.json
  cluster/testdata/cluster_lock_v1_3_0.json
  cluster/testdata/cluster_lock_v1_4_0.json
  cluster/testdata/cluster_lock_v1_5_0.json
  cluster/testdata/cluster_lock_v1_6_0.json
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  cmd/createdkg.go
  cmd/createdkg_internal_test.go
  dkg/keycast_internal_test.go
  testutil/compose/define.go
  testutil/compose/lock.go
  testutil/compose/testdata/TestDockerCompose_define_dkg_template.golden
  testutil/compose/testdata/TestDockerCompose_define_dkg_yml.golden
  testutil/compose/testdata/TestDockerCompose_lock_create_template.golden
  testutil/compose/testdata/TestDockerCompose_lock_create_yml.golden
Labels: merge when ready

#1833 *: change license to BSL
  LICENSE
Labels: merge when ready
