Repository ObolNetwork/charon, pull requests merged in 2023-03, with the labels that each got.

#1838 core/consensus: add support for pointer values on the wire
  .github/workflows/golangci-lint.yml
  app/app.go
  app/simnet_test.go
  core/consensus/component.go
  core/consensus/component_test.go
  core/consensus/msg.go
  core/consensus/msg_internal_test.go
  core/consensus/sniffed_internal_test.go
  core/consensus/transport.go
  core/corepb/v1/consensus.pb.go
  core/corepb/v1/consensus.proto
  dkg/disk.go
  eth2util/keystore/keystore.go
  testutil/genchangelog/main.go
Labels: merge when ready

#1845 *: fix `golangci-lint` issues
  .github/workflows/golangci-lint.yml
  .pre-commit-config.yaml
  cmd/createdkg.go
  core/consensus/sniffed_internal_test.go
  core/consensus/transport.go
  dkg/disk.go
  eth2util/keystore/keystore.go
Labels: merge when ready

#1852 gomod: upgrade github.com/bufbuild/buf to v1.15.0
  core/corepb/v1/consensus.pb.go
  go.mod
  go.sum
Labels: merge when ready

#1855 app/version: bump to version v0.14.0
  app/version/version.go
Labels: merge when ready

#1856 app: promote `herumi_bls` feature flag to stable
  app/app.go
  app/featureset/featureset.go
Labels: merge when ready, refactor

#1861 core/consensus: fix msg parsing issue
  core/consensus/msg.go
  core/consensus/msg_internal_test.go
Labels: merge when ready

#1862 core/consensus: swap value vs hash parsing
  core/consensus/msg.go
  core/consensus/msg_internal_test.go
Labels: merge when ready

#1865 *: update to go1.20.2
  .github/workflows/golangci-lint.yml
  .github/workflows/govulncheck.yml
  .github/workflows/pre-commit.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/track-pr.yml
  .github/workflows/verify-pr.yml
  .golangci.yml
  .pre-commit-config.yaml
  Dockerfile
  testutil/promrated/Dockerfile
  testutil/random.go
Labels: merge when ready

#1864 app/eth2wrap: add proposer index in synthetic blocks
  app/eth2wrap/synthproposer.go
  core/validatorapi/router.go
Labels: merge when ready

#1866 core: fix data race in scheduler
  core/scheduler/scheduler.go
Labels: merge when ready

#1868 readme: update nimbus attestation status
  README.md
Labels: merge when ready

#1869 cmd/createcluster: handle multiple addresses with remote definition
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
Labels: merge when ready

#1871 p2p: improve read timeout errors
  p2p/receive.go
Labels: merge when ready

#1872 p2p: improve read timeout logs
  p2p/receive.go
Labels: merge when ready

#1875 k1util: trim newline when decoding `charon-enr-private-key`
  app/k1util/k1util.go
  app/k1util/k1util_test.go
Labels: merge when ready

#1877 app/version: bump to v0.14.1
  app/version/version.go
Labels: merge when ready

#1880 dockerfile: fix container healthcheck
  Dockerfile
Labels: merge when ready

#1882 precommit: only check major go version locally
  .pre-commit-config.yaml
Labels: merge when ready

#1873 cmd/createcluster: fix split keys bug for multiple validators
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  cmd/createdkg.go
  cmd/createdkg_internal_test.go
Labels: merge when ready

#1885 p2p: add support for delimited wire protocol upgrades
  go.mod
  p2p/metrics.go
  p2p/receive.go
  p2p/receive_test.go
  p2p/sender.go
  p2p/sender_internal_test.go
Labels: merge when ready

#1891 relay: add streams outbound limit
  cmd/relay/p2p.go
Labels: merge when ready

#1890 *: enable delimited wire protocol upgrade
  app/peerinfo/adhoc.go
  app/peerinfo/peerinfo.go
  core/consensus/component.go
  core/consensus/transport.go
  core/parsigex/parsigex.go
  core/priority/prioritiser.go
Labels: merge when ready

#1893 dkg/bcast: implement reliable broadcast protocol
  dkg/bcast/client.go
  dkg/bcast/helpers.go
  dkg/bcast/impl.go
  dkg/bcast/impl_test.go
  dkg/bcast/server.go
  dkg/dkgpb/v1/bcast.pb.go
  dkg/dkgpb/v1/bcast.proto
  testutil/random.go
Labels: merge when ready

#1896 dkg: refactor to reliable broadcast
  dkg/dkg.go
  dkg/dkgpb/v1/frost.pb.go
  dkg/dkgpb/v1/frost.proto
  dkg/frost.go
  dkg/frost_internal_test.go
  dkg/frostp2p.go
Labels: merge when ready

#1899 dkg: revert test debugging change
  dkg/frost_internal_test.go
Labels: merge when ready

#1903 p2p: always ensure relay connection
  p2p/relay.go
Labels: merge when ready

#1904 core/consensus: remove support for legacy wire protocol
  app/app.go
  app/simnet_test.go
  app/version/version.go
  core/consensus/component.go
  core/consensus/component_test.go
  core/consensus/msg.go
  core/consensus/msg_internal_test.go
  core/consensus/transport.go
Labels: merge when ready

#1907 dkg: add content type to lock file post
  app/obolapi/api.go
  app/obolapi/api_test.go
Labels: merge when ready

#1908 dkg: remove backticks
  app/obolapi/api.go
  eth2util/keymanager/keymanager.go
Labels: merge when ready

#1909 dkg: fixes publish arg and signature_aggregate creation
  cmd/createcluster.go
  cmd/dkg.go
Labels: merge when ready

#1905 cmd/relay: disable resource manager
  app/app.go
  app/app_test.go
  cmd/relay/p2p.go
  dkg/dkg.go
  p2p/relay.go
Labels: merge when ready

#1902 app/genssz: implement ssz hash generator
  app/genssz/genssz.go
  app/genssz/template.go
  app/genssz/testdata/example.go
  app/genssz/testdata/ssz_gen.go
  app/genssz/types.go
Labels: merge when ready

#1914 core/validatorapi: add an error log to debug lodestar integration
  core/validatorapi/validatorapi.go
  dkg/disk.go
Labels: merge when ready

#1924 dkg/sync: fix shutdown reconnect deadlock
  dkg/sync/client.go
Labels: merge when ready

#1927 app/version: bump v0.14.4
  app/version/version.go
Labels: merge when ready

#1920 github/workflows: only build images for protected branches
  .github/workflows/build-push-deploy.yml
Labels: merge when ready

#1876 combine: explicit output directory, new output keystore directory format
  cmd/combine.go
  combine/combine.go
  combine/combine_test.go
Labels: merge when ready, refactor

#1931 cmd/combine: move combine package
  cmd/combine.go
  cmd/combine/combine.go
  cmd/combine/combine_test.go
Labels: merge when ready

#1932 app/version: bump version to v0.15.0-dev
  app/version/version.go
Labels: merge when ready

#1935 dkg: better checks for data directory cleanliness
  dkg/disk.go
  dkg/disk_internal_test.go
  dkg/dkg.go
Labels: enhancement, merge when ready

#1929 testutil/beaconmock: initial PoC for beacon fuzz
  app/app.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/genwrap/genwrap.go
  cmd/run.go
  docs/configuration.md
  go.mod
  go.sum
  testutil/beaconmock/beaconmock.go
  testutil/beaconmock/beaconmock_fuzz.go
  testutil/beaconmock/headproducer.go
  testutil/beaconmock/options.go
  testutil/compose/compose/main.go
  testutil/compose/config.go
  testutil/compose/lock.go
  testutil/compose/testdata/TestDockerCompose_run_template.golden
  testutil/compose/testdata/TestDockerCompose_run_yml.golden
  testutil/compose/testdata/TestNewDefaultConfig.golden
Labels: merge when ready

#1933 cluster: release v1.6 of cluster definition
  cluster/version.go
Labels: merge when ready

#1936 dkg: log peer summary at the start of DKG
  dkg/dkg.go
Labels: merge when ready

#1937 p2p: fix ping service race condition
  p2p/ping.go
Labels: merge when ready

#1941 dkg: improve dkg logs for empty addresses
  dkg/dkg.go
Labels: merge when ready

#1942 dkg: fix race condition in keycast
  dkg/keycast.go
Labels: merge when ready

#1946 p2p: move ActivationThresh in a sync.Once
  p2p/p2p.go
Labels: bug, merge when ready

#1947 dkg: fix race condition in exchanger test
  dkg/exchanger_internal_test.go
Labels: merge when ready

#1944 app/featureset: fix data race in Enabled
  app/featureset/config.go
  app/featureset/featureset.go
Labels: bug, merge when ready

#1950 core/aggsigdb: refactor concurrent access issue in test
  core/aggsigdb/memory_internal_test.go
Labels: bug, merge when ready

#1953 core/scheduler: fix data race in tests
  core/scheduler/scheduler_test.go
Labels: bug, merge when ready

#1952 ci: run tests with `-race` flag
  .github/workflows/test.yml
  .pre-commit/run_tests.sh
Labels: enhancement, merge when ready

#1954 p2p: disable dynamic length delimited protocol negotation
  p2p/receive_test.go
  p2p/sender.go
Labels: merge when ready

#1955 dkg/sync: improve client version mismatch errors
  dkg/sync/client.go
Labels: merge when ready

#1958 p2p: support zero length request protos
  app/peerinfo/adhoc_test.go
  p2p/receive_test.go
  p2p/sender.go
  p2p/sender_internal_test.go
Labels: merge when ready

#1963 github/workflows: isolate integration tests
  .github/workflows/test.yml
  app/simnet_test.go
Labels: merge when ready

#1966 testutil/validatormock: fix concurrent access issue
  testutil/validatormock/attest.go
Labels: merge when ready

#1972 testutil/integration: move app tests
  .github/workflows/test.yml
  testutil/integration/doc.go
  testutil/integration/helpers_test.go
  testutil/integration/infosync_test.go
  testutil/integration/ping_test.go
  testutil/integration/simnet_test.go
Labels: merge when ready

#1974 testutil/integration: fix parsigexmem race
  core/parsigex/memory.go
  core/parsigex/memory_test.go
  testutil/integration/simnet_test.go
Labels: merge when ready

#1976 cmd: fix publish test timeout
  cmd/createcluster_internal_test.go
Labels: merge when ready

#1977 app: fix data race in `setFeeRecipient`
  app/app.go
Labels: merge when ready

#1983 readme: point to dvt.obol.tech for project status
  README.md
Labels: merge when ready

#1982 dkg: enable peerinfo server
  dkg/dkg.go
Labels: merge when ready

#1985 *: fix more test issues
  dkg/dkg.go
  dkg/sync/sync_test.go
  p2p/relay.go
Labels: merge when ready
