Repository ObolNetwork/charon, pull requests merged in 2023-10, with the labels that each got.

#2627 beaconmock: add `MIN_EPOCHS_FOR_BLOCK_REQUESTS`
  testutil/beaconmock/static.json
Labels: merge when ready, branch-release

#2626 gomod: upgrade libp2p to v0.29.2
  core/aggsigdb/memory_internal_test.go
  go.mod
  go.sum
  main.go
Labels: merge when ready, branch-release

#2625 cmd/combine: ensure output dir exists
  cmd/combine/combine.go
  cmd/combine/combine_test.go
  eth2util/keystore/keystore.go
  eth2util/keystore/keystore_test.go
Labels: merge when ready, branch-release

#2628 eth2util: add holesky
  cmd/createcluster.go
  cmd/createdkg.go
  eth2util/network.go
  eth2util/network_test.go
Labels: merge when ready, branch-release

#2630 eth2util/deposit: bump deposit cli version
  eth2util/deposit/deposit.go
  eth2util/deposit/testdata/TestMarshalDepositData.golden
Labels: merge when ready, branch-release

#2629 eth2util: fix fork version
  eth2util/network.go
Labels: merge when ready, branch-release

#2545 testutil/validatormock: refactor vmock
  app/app.go
  app/vmock.go
  core/scheduler/scheduler.go
  testutil/compose/auto.go
  testutil/compose/compose/main.go
  testutil/compose/run.go
  testutil/compose/smoke/smoke_test.go
  testutil/validatormock/component.go
  testutil/validatormock/meta.go
  testutil/validatormock/propose.go
  testutil/validatormock/propose_test.go
Labels: merge when ready

#2635 core: update interfaces
  cmd/createcluster.go
  core/corepb/v1/core.pb.go
  core/corepb/v1/core.proto
  core/eth2signeddata.go
  core/eth2signeddata_test.go
  core/fetcher/fetcher.go
  core/fetcher/fetcher_test.go
  core/parsigdb/memory.go
  core/proto.go
  core/proto_test.go
  core/sigagg/sigagg.go
  core/sigagg/sigagg_test.go
  core/signeddata.go
  core/signeddata_test.go
  core/tracker/tracker.go
  core/tracker/tracker_internal_test.go
  core/types.go
  dkg/dkg.go
  eth2util/registration/registration_test.go
  go.mod
  go.sum
  testutil/integration/simnet_test.go
Labels: merge when ready

#2638 *: bump go version
  .github/workflows/golangci-lint.yml
  .github/workflows/govulncheck.yml
  .github/workflows/nightly-tests.yml
  .github/workflows/pre-commit.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/verify-pr.yml
  .golangci.yml
  .pre-commit-config.yaml
  Dockerfile
  app/peerinfo/peerinfo.go
  cluster/definition.go
  cluster/deposit.go
  cluster/distvalidator.go
  cluster/lock.go
  cluster/operator.go
  cluster/registration.go
  eth2util/keystore/keystore.go
  go.mod
  go.sum
  testutil/promrated/Dockerfile
  testutil/verifypr/verify.go
Labels: merge when ready

#2584 eth2util/keystore: lower amount of loadStoreWorkers
  eth2util/keystore/keystore.go
Labels: merge when ready

#2645 testutil/validatormock: fix simnet tests
  testutil/validatormock/component.go
Labels: merge when ready

#2649 vmock: change start time of sync selections to start of slot
  testutil/validatormock/component.go
Labels: merge when ready

#2648 *: bump go version
  .github/workflows/golangci-lint.yml
  .github/workflows/govulncheck.yml
  .github/workflows/nightly-tests.yml
  .github/workflows/pre-commit.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/verify-pr.yml
  .golangci.yml
  .pre-commit-config.yaml
  Dockerfile
  cluster/definition.go
  cluster/deposit.go
  cluster/distvalidator.go
  cluster/lock.go
  cluster/operator.go
  cluster/registration.go
  eth2util/keystore/keystore.go
  go.mod
  go.sum
  testutil/integration/simnet_test.go
  testutil/promrated/Dockerfile
  testutil/verifypr/verify.go
Labels: branch-release, v0.17.1

#2647 testutil/genchangelog: force fetch tags
  testutil/genchangelog/main.go
Labels: branch-release, v0.17.1

#2651 testutil/validatormock: remove pseudo code
  testutil/validatormock/synccontributionflow_test.go
Labels: merge when ready

#2586 eth2util/keymanager: dynamically set request timeout
  eth2util/keymanager/keymanager.go
Labels: merge when ready

#2664 cmd/combine: allow threshold number of keys to combine
  cmd/combine/combine.go
  cmd/combine/combine_test.go
Labels: merge when ready

#2652 testutil/genchangelog: ignore rc's, template changes
  app/version/version.go
  app/version/version_test.go
  testutil/genchangelog/main.go
  testutil/genchangelog/main_internal_test.go
  testutil/genchangelog/template.md
  testutil/genchangelog/testdata/TestParsePRs_parsed_prs.golden
  testutil/genchangelog/testdata/TestParsePRs_template.golden
  testutil/genchangelog/testdata/TestParsePRs_template_data.golden
Labels: merge when ready, v0.18.0
