Repository ObolNetwork/charon, pull requests merged in 2024-11, with the labels that each got.

#3327 *: consensus abstraction
  app/app.go
  cluster/manifest/mutationlegacylock.go
  cluster/manifestpb/v1/manifest.pb.go
  cluster/manifestpb/v1/manifest.proto
  cmd/createcluster.go
  cmd/createdkg.go
  cmd/run.go
  cmd/version.go
  cmd/version_internal_test.go
  core/consensus/controller.go
  core/consensus/controller_test.go
  core/consensus/debugger.go
  core/consensus/debugger_internal_test.go
  core/consensus/metrics.go
  core/consensus/metrics/metrics.go
  core/consensus/metrics/metrics_test.go
  core/consensus/mocks/debugger.go
  core/consensus/protocols/protocols.go
  core/consensus/protocols/protocols_test.go
  core/consensus/qbft/msg.go
  core/consensus/qbft/msg_internal_test.go
  core/consensus/qbft/qbft.go
  core/consensus/qbft/qbft_internal_test.go
  core/consensus/qbft/qbft_test.go
  core/consensus/qbft/sniffed_internal_test.go
  core/consensus/qbft/sniffer.go
  core/consensus/qbft/sniffer_internal_test.go
  core/consensus/qbft/strategysim_internal_test.go
  core/consensus/qbft/testdata/TestDebugRoundChange_empty-1.golden
  core/consensus/qbft/testdata/TestDebugRoundChange_empty-2.golden
  core/consensus/qbft/testdata/TestDebugRoundChange_quorum.golden
  core/consensus/qbft/testdata/TestHashProto.golden
  core/consensus/qbft/transport.go
  core/consensus/utils/instance_io.go
  core/consensus/utils/instance_io_test.go
  core/consensus/utils/roundtimer.go
  core/consensus/utils/roundtimer_test.go
  core/consensus/wrapper.go
  core/consensus/wrapper_internal_test.go
  core/corepb/v1/consensus.pb.go
  core/corepb/v1/consensus.proto
  core/deadline.go
  core/interfaces.go
  core/mocks/consensus.go
  core/mocks/deadliner.go
  docs/README.md
  docs/configuration.md
  docs/consensus.md
  docs/metrics.md
  p2p/sender_internal_test.go
Labels: merge when ready

#3353 cmd: increase Obol API timeout for exits
  cmd/exit.go
Labels: merge when ready

#3351 *: add needs to trigger
  .github/workflows/release.yml
Labels: merge when ready

#3364 docs: fix typos in documentation files
  docs/dkg.md
  docs/goguidelines.md
  docs/structure.md
Labels: merge when ready

#3367 docs: fix typos and improve clarity in documentation files
  cmd/markdown_internal_test.go
  docs/branching.md
  docs/contributing.md
  docs/dkg.md
  docs/metrics.md
Labels: merge when ready

#3368 cmd: add cluster lock and cluster definition to test peers
  cmd/testpeers.go
  cmd/testpeers_internal_test.go
Labels: merge when ready

#3361 cmd: beacon node simulation
  cmd/test.go
  cmd/testbeacon.go
  cmd/testbeacon_internal_test.go
  cmd/testmev.go
  cmd/testpeers.go
Labels: merge when ready

#3377 cmd: group and move functions in test command
  cmd/testbeacon.go
  cmd/testmev.go
  cmd/testpeers.go
  cmd/testperformance.go
  cmd/testvalidator.go
Labels: branch-invalid

#3369 docs: typo in README.md
  docs/README.md
Labels: merge when ready

#3370 cmd: test command UX
  cmd/ascii.go
  cmd/cmd.go
  cmd/test.go
  cmd/testall.go
  cmd/testbeacon.go
  cmd/testmev.go
  cmd/testpeers.go
  cmd/testpeers_internal_test.go
  cmd/testperformance.go
  cmd/testvalidator.go
Labels: merge when ready

#3378 cmd: charon test mev create block tests
  cmd/test.go
  cmd/testbeacon.go
  cmd/testmev.go
  cmd/testmev_internal_test.go
  go.mod
  go.sum
Labels: merge when ready

#3379 cmd: add version check to beacon node tests
  app/log/loki/lokipb/v1/loki.pb.go
  app/peerinfo/peerinfopb/v1/peerinfo.pb.go
  app/protonil/testdata/v1/test.pb.go
  cluster/manifestpb/v1/manifest.pb.go
  cmd/testbeacon.go
  cmd/testbeacon_internal_test.go
  core/corepb/v1/consensus.pb.go
  core/corepb/v1/core.pb.go
  core/corepb/v1/parsigex.pb.go
  core/corepb/v1/priority.pb.go
  dkg/dkgpb/v1/bcast.pb.go
  dkg/dkgpb/v1/frost.pb.go
  dkg/dkgpb/v1/nodesigs.pb.go
  dkg/dkgpb/v1/sync.pb.go
Labels: merge when ready

#3380 cmd: rename test performance to test infra command
  cmd/ascii.go
  cmd/cmd.go
  cmd/test.go
  cmd/testall.go
  cmd/testperformance.go
  cmd/testperformance_internal_test.go
Labels: merge when ready

#3381 *: fix trigger dispatch repo
  .github/workflows/build-push-deploy.yml
Labels: merge when ready

#3384 cmd: test command file output improvements
  cmd/test.go
  cmd/testbeacon.go
  cmd/testbeacon_internal_test.go
  cmd/testinfra.go
  cmd/testinfra_internal_test.go
  cmd/testmev.go
  cmd/testmev_internal_test.go
  cmd/testpeers.go
  cmd/testpeers_internal_test.go
  cmd/testvalidator.go
  cmd/testvalidator_internal_test.go
  go.mod
  go.sum
Labels: merge when ready

#3385 cmd: add custom number of validators beacon simulation test
  cmd/cmd.go
  cmd/testall.go
  cmd/testbeacon.go
  cmd/testbeacon_internal_test.go
  cmd/testinfra.go
  cmd/testinfra_internal_test.go
  cmd/testmev.go
  cmd/testmev_internal_test.go
  cmd/testpeers.go
  cmd/testpeers_internal_test.go
  cmd/testvalidator.go
  cmd/testvalidator_internal_test.go
Labels: merge when ready

#3387 *: bump linter v1.62
  .github/workflows/golangci-lint.yml
  .golangci.yml
  .pre-commit/run_linter.sh
  app/obolapi/api_internal_test.go
  cmd/addvalidators_internal_test.go
  core/priority/component.go
Labels: merge when ready

#3389 Dockerfile: add back chown
  Dockerfile
Labels: merge when ready

#3390 cmd: test command flags update
  cmd/cmd.go
  cmd/duration.go
  cmd/duration_test.go
  cmd/test.go
  cmd/testbeacon.go
  cmd/testinfra.go
  cmd/testmev.go
  cmd/testmev_internal_test.go
  cmd/testpeers.go
  cmd/testpeers_internal_test.go
Labels: merge when ready

#3392 *: release v1.2-rc2
  .github/workflows/golangci-lint.yml
  .golangci.yml
  .pre-commit/run_linter.sh
  Dockerfile
  app/obolapi/api_internal_test.go
  cmd/addvalidators_internal_test.go
  cmd/cmd.go
  cmd/duration.go
  cmd/duration_test.go
  cmd/test.go
  cmd/testbeacon.go
  cmd/testinfra.go
  cmd/testmev.go
  cmd/testmev_internal_test.go
  cmd/testpeers.go
  cmd/testpeers_internal_test.go
  core/priority/component.go
  go.mod
  go.sum
Labels: merge when ready, branch-release
