Repository ObolNetwork/charon, pull requests merged in 2024-01, with the labels that each got.

#2775 app/version: bump to v0.19-rc
  app/version/version.go
Labels: merge when ready, branch-release

#2774 app/version: bump version to v0.20-dev
  app/version/version.go
Labels: merge when ready

#2785 docs: fix docs from small prs
  core/validatorapi/router.go
  docs/contributing.md
  docs/dkg.md
  docs/goguidelines.md
Labels: merge when ready

#2782 core: removed leadercast leftovers
  core/proto.go
  core/unsigneddata.go
  docs/structure.md
Labels: merge when ready

#2783 core: addressed some panic instances
  core/proto.go
  core/tracing.go
  eth2util/rlp/rlp.go
Labels: merge when ready

#2788 core/validatorapi: correct error return
  core/validatorapi/validatorapi.go
Labels: merge when ready, v0.19.0

#2790 *: revert Herumi to v1.32.1
  go.mod
  go.sum
Labels: merge when ready

#2795 core: checking keymanager address
  cmd/createcluster.go
  dkg/dkg.go
  dkg/dkg_internal_test.go
  eth2util/keymanager/keymanager.go
  eth2util/keymanager/keymanager_test.go
Labels: merge when ready

#2800 core: fixing DutyDB Store function
  core/dutydb/memory.go
Labels: merge when ready

#2801 core: removed unused allowlist and denylist flags
  cmd/cmd_internal_test.go
  cmd/run.go
  docs/configuration.md
  p2p/config.go
Labels: merge when ready

#2797 dkg: strengthen logic for steps update
  dkg/dkg.go
  dkg/sync/client.go
  dkg/sync/server.go
  dkg/sync/server_internal_test.go
Labels: merge when ready

#2808 cmd: don't bind debug endpoints by default
  app/app.go
  app/lifecycle/order.go
  app/lifecycle/orderstart_string.go
  app/lifecycle/orderstop_string.go
  app/monitoringapi.go
  cmd/run.go
  docs/configuration.md
Labels: merge when ready, v0.20.0

#2806 app: eth2wrap best selector refactoring
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/genwrap/genwrap.go
Labels: merge when ready, v0.20.0

#2809 core: remove unimportant todos
  core/proto.go
  core/validatorapi/router_internal_test.go
Labels: merge when ready

#2810 cmd: fixing builder registration timestamp
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
Labels: merge when ready

#2813 *: more warnings on HTTP URLs
  dkg/disk.go
  p2p/bootnode.go
Labels: merge when ready

#2814 gomod: update Herumi BLS to v1.33.0
  Dockerfile
  go.mod
  go.sum
Labels: merge when ready

#2815 testutil: fixed promrated.go
  testutil/promrated/promrated.go
  testutil/promrated/promrated_internal_test.go
Labels: merge when ready

#2816 cmd: add secondary charon relay
  cmd/cmd_internal_test.go
  cmd/run.go
  docs/configuration.md
Labels: merge when ready

#2818 github/workflows: fuzz tests on nightly
  .github/workflows/nightly-tests.yml
  .github/workflows/test.yml
Labels: merge when ready

#2819 eth2util: remove legacy signed epoch
  eth2util/types.go
  eth2util/types_test.go
Labels: merge when ready

#2817 cmd/relay: bind debug and monitoring address separately
  cmd/debug_tools.go
  cmd/debug_tools_internal_test.go
  cmd/relay.go
  cmd/relay/relay.go
  cmd/run.go
  docs/configuration.md
Labels: merge when ready, v0.20.0, qs-audit

#2821 *: implement audit fixes
  app/app.go
  app/lifecycle/order.go
  app/lifecycle/orderstart_string.go
  app/lifecycle/orderstop_string.go
  app/monitoringapi.go
  cmd/cmd_internal_test.go
  cmd/createcluster.go
  cmd/debug_tools.go
  cmd/debug_tools_internal_test.go
  cmd/relay.go
  cmd/relay/relay.go
  cmd/run.go
  core/dutydb/memory.go
  core/proto.go
  core/tracing.go
  core/unsigneddata.go
  core/validatorapi/router_internal_test.go
  dkg/bcast/client.go
  dkg/bcast/helpers.go
  dkg/bcast/impl.go
  dkg/bcast/impl_test.go
  dkg/bcast/server.go
  dkg/disk.go
  dkg/dkg.go
  dkg/dkg_internal_test.go
  dkg/dkgpb/v1/bcast.pb.go
  dkg/dkgpb/v1/bcast.proto
  dkg/frostp2p.go
  dkg/nodesigs.go
  dkg/sync/client.go
  dkg/sync/server.go
  dkg/sync/server_internal_test.go
  docs/configuration.md
  docs/structure.md
  eth2util/keymanager/keymanager.go
  eth2util/keymanager/keymanager_test.go
  eth2util/rlp/rlp.go
  eth2util/types.go
  eth2util/types_test.go
  p2p/bootnode.go
  p2p/config.go
Labels: merge when ready, branch-release

#2830 p2p: fixed flakey TestWithSendTimeout
  p2p/sender_test.go
Labels: merge when ready

#2822 eth2util: new deposit message with amount
  cmd/addvalidators.go
  cmd/createcluster.go
  dkg/dkg.go
  dkg/dkg_internal_test.go
  eth2util/deposit/deposit.go
  eth2util/deposit/deposit_test.go
Labels: merge when ready

#2832 core: using `url.ParseRequestURI`
  app/eth2wrap/eth2wrap_test.go
  app/eth2wrap/httpwrap.go
  app/obolapi/api_test.go
  cmd/cmd.go
  cmd/createcluster.go
  core/validatorapi/router.go
  eth2util/keymanager/keymanager.go
  p2p/bootnode.go
  testutil/beaconmock/headproducer_internal_test.go
  testutil/promrated/prometheus.go
  testutil/url.go
  testutil/verifypr/verify.go
Labels: merge when ready

#2820 cmd: --deposit-amounts flag
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  cmd/testdata/TestCreateCluster_four_partial_deposits_files.golden
  cmd/testdata/TestCreateCluster_four_partial_deposits_output.golden
  cmd/testdata/TestCreateCluster_two_partial_deposits_files.golden
  cmd/testdata/TestCreateCluster_two_partial_deposits_output.golden
  eth2util/deposit/deposit.go
  eth2util/deposit/deposit_test.go
Labels: merge when ready

#2823 cluster: definition v1.8
  cluster/cluster_test.go
  cluster/definition.go
  cluster/deposit.go
  cluster/deposit_internal_test.go
  cluster/distvalidator.go
  cluster/lock.go
  cluster/ssz.go
  cluster/testdata/cluster_definition_v1_8_0.json
  cluster/testdata/cluster_lock_v1_8_0.json
  cluster/version.go
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  dkg/dkg.go
  dkg/dkg_test.go
Labels: merge when ready

#2839 cluster: partial deposits output
  cluster/cluster_internal_test.go
  cluster/cluster_test.go
  cluster/definition.go
  cluster/test_cluster.go
  cluster/version.go
  cmd/addvalidators.go
  cmd/createcluster.go
  cmd/createdkg.go
  cmd/testdata/TestCreateCluster_custom_testnet_flags_files.golden
  cmd/testdata/TestCreateCluster_custom_testnet_flags_output.golden
  cmd/testdata/TestCreateCluster_four_partial_deposits_files.golden
  cmd/testdata/TestCreateCluster_four_partial_deposits_output.golden
  cmd/testdata/TestCreateCluster_goerli_files.golden
  cmd/testdata/TestCreateCluster_goerli_output.golden
  cmd/testdata/TestCreateCluster_simnet_files.golden
  cmd/testdata/TestCreateCluster_simnet_output.golden
  cmd/testdata/TestCreateCluster_solo_flow_definition_from_disk_files.golden
  cmd/testdata/TestCreateCluster_solo_flow_definition_from_disk_output.golden
  cmd/testdata/TestCreateCluster_solo_flow_definition_from_network_files.golden
  cmd/testdata/TestCreateCluster_solo_flow_definition_from_network_output.golden
  cmd/testdata/TestCreateCluster_splitkeys_files.golden
  cmd/testdata/TestCreateCluster_splitkeys_output.golden
  cmd/testdata/TestCreateCluster_splitkeys_with_cluster_definition_files.golden
  cmd/testdata/TestCreateCluster_splitkeys_with_cluster_definition_output.golden
  cmd/testdata/TestCreateCluster_test_with_fee_recipient_and_withdrawal_addresses_files.golden
  cmd/testdata/TestCreateCluster_test_with_fee_recipient_and_withdrawal_addresses_output.golden
  cmd/testdata/TestCreateCluster_two_partial_deposits_files.golden
  cmd/testdata/TestCreateCluster_two_partial_deposits_output.golden
  dkg/dkg.go
  dkg/dkg_internal_test.go
  docs/configuration.md
  eth2util/deposit/deposit.go
  eth2util/deposit/deposit_test.go
Labels: merge when ready
