Repository ObolNetwork/charon, pull requests merged in 2024-10, with the labels that each got.

#3309 dkg: fixed TestSyncFlow
  dkg/dkg_test.go
Labels: merge when ready

#3297 cmd: move threshold check to CLI level
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  cmd/createdkg.go
  cmd/createdkg_internal_test.go
  tbls/herumi.go
Labels: merge when ready

#3296 cmd: enable exit all
  cmd/exit.go
Labels: merge when ready

#3316 test: fix test performance flaky test
  cmd/createdkg_internal_test.go
  cmd/testpeers_internal_test.go
Labels: merge when ready

#3307 *: removing mutable config
  app/app.go
  app/priorities.go
  core/config.go
  core/fetcher/fetcher.go
  core/fetcher/fetcher_test.go
  core/infosync/infosync.go
  core/scheduler/scheduler.go
  core/scheduler/scheduler_internal_test.go
  core/scheduler/scheduler_test.go
  core/validatorapi/router.go
  core/validatorapi/router_internal_test.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_internal_test.go
  core/validatorapi/validatorapi_test.go
  testutil/helpers.go
  testutil/integration/nightly_dkg_test.go
Labels: merge when ready

#3310 *: create automate pr for release
  .github/workflows/release.yml
Labels: merge when ready

#3318 *: cluster definition v1.9
  cluster/cluster_internal_test.go
  cluster/cluster_test.go
  cluster/definition.go
  cluster/lock.go
  cluster/ssz.go
  cluster/test_cluster.go
  cluster/testdata/cluster_definition_v1_9_0.json
  cluster/testdata/cluster_lock_v1_9_0.json
  cluster/version.go
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  cmd/createdkg.go
  cmd/createdkg_internal_test.go
  core/consensus/component.go
  core/consensus/component_test.go
Labels: merge when ready

#3292 core/validatorapi: check proposal data against consensus one
  app/eth2wrap/eth2wrap_test.go
  app/eth2wrap/synthproposer_test.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_test.go
  eth2util/registration/registration_test.go
  eth2util/signing/signing.go
  eth2util/signing/signing_test.go
  testutil/beaconmock/options.go
  testutil/beaconmock/server_test.go
  testutil/beaconmock/static.json
  testutil/integration/simnet_test.go
Labels: merge when ready, protocol

#3331 *: bumped protoc-gen-go
  app/log/loki/lokipb/v1/loki.pb.go
  app/peerinfo/peerinfopb/v1/peerinfo.pb.go
  app/protonil/testdata/v1/test.pb.go
  cluster/manifestpb/v1/manifest.pb.go
  core/corepb/v1/consensus.pb.go
  core/corepb/v1/core.pb.go
  core/corepb/v1/parsigex.pb.go
  core/corepb/v1/priority.pb.go
  core/validatorapi/validatorapi_test.go
  dkg/dkgpb/v1/bcast.pb.go
  dkg/dkgpb/v1/frost.pb.go
  dkg/dkgpb/v1/nodesigs.pb.go
  dkg/dkgpb/v1/sync.pb.go
Labels: merge when ready

#3332 testutil: fixed smoke test
  testutil/compose/smoke/smoke_test.go
  testutil/compose/static/lodestar/run.sh
Labels: merge when ready

#3281 *: optimize Dockerfile
  Dockerfile
Labels: merge when ready

#3321 github: use minor go versions in pipelines
  .github/actions/setup-go/action.yml
  .golangci.yml
Labels: merge when ready

#3317 exit: add custom testnet flags for exits
  cmd/exit.go
  cmd/exit_broadcast.go
  cmd/exit_fetch.go
  cmd/exit_list.go
  cmd/exit_sign.go
Labels: merge when ready

#3343 testutil/integration: fix nightly test behavior
  testutil/integration/nightly_dkg_test.go
Labels: merge when ready

#3349 *: update bls-eth-go-binary
  go.mod
  go.sum
Labels: branch-release

#3347 *: improve logging and error handling for exits
  app/obolapi/api.go
  app/obolapi/api_internal_test.go
  app/obolapi/exit.go
  cmd/cmd.go
  cmd/exit.go
  cmd/exit_broadcast.go
  cmd/exit_broadcast_internal_test.go
  cmd/exit_fetch.go
  cmd/exit_fetch_internal_test.go
  cmd/exit_list.go
  cmd/exit_list_internal_test.go
  cmd/exit_sign.go
  cmd/exit_sign_internal_test.go
  testutil/obolapimock/obolapi_exit.go
Labels: merge when ready
