Repository ObolNetwork/charon, pull requests merged in 2025-02, with the labels that each got.

#3492 *: fix tag latest with strict rule
  .github/workflows/build-push-deploy.yml
Labels: merge when ready, cicd

#3494 fix: tag latest with startsWith
  .github/workflows/build-push-deploy.yml
Labels: merge when ready, cicd

#3495 fix: change type raw to semver to tag latest
  .github/workflows/build-push-deploy.yml
Labels: merge when ready, cicd

#3497 fix: latest with startsWith and github.ref
  .github/workflows/build-push-deploy.yml
Labels: merge when ready, cicd

#3437 ci: optimize Docker build workflow and update actions
  .github/workflows/build-push-deploy-promrated.yaml
Labels: merge when ready, cicd

#3501 *: fix inclusion aggregation bits for Electra
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/genwrap/genwrap.go
  app/eth2wrap/httpwrap.go
  app/eth2wrap/lazy.go
  app/eth2wrap/mocks/client.go
  app/eth2wrap/multi.go
  core/signeddata_test.go
  core/tracker/inclusion.go
  core/tracker/inclusion_internal_test.go
  core/unsigneddata_test.go
  core/validatorapi/router_internal_test.go
  eth2util/statecomm/statecomm.go
  testutil/beaconmock/beaconmock.go
  testutil/random.go
Labels: merge when ready, electra

#3515 app: add headers to httpwrap
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_test.go
  app/eth2wrap/httpwrap.go
  app/obolapi/exit_test.go
  app/vmock.go
  core/validatorapi/router_internal_test.go
Labels: merge when ready

#3511 app/eth2wrap: fix faulty fallback test
  app/eth2wrap/eth2wrap_test.go
Labels: merge when ready

#3500 fix: refresh validator by slot instead of by head
  app/app.go
  app/eth2wrap/valcache.go
  app/eth2wrap/valcache_test.go
Labels: merge when ready

#3520 *: compounding flag
  app/eth2wrap/eth2wrap_test.go
  cluster/cluster_internal_test.go
  cluster/cluster_test.go
  cluster/definition.go
  cluster/examples/cluster-definition-006.json
  cluster/manifest/load_test.go
  cluster/manifest/mutationlegacylock.go
  cluster/manifestpb/v1/manifest.pb.go
  cluster/manifestpb/v1/manifest.proto
  cluster/ssz.go
  cluster/test_cluster.go
  cluster/testdata/cluster_definition_v1_10_0.json
  cluster/testdata/cluster_lock_v1_10_0.json
  cmd/addvalidators.go
  cmd/createcluster.go
  cmd/createdkg.go
  cmd/createdkg_internal_test.go
  cmd/testdata/Test_viewClusterManifest.golden
  dkg/disk.go
  dkg/dkg.go
  dkg/dkg_internal_test.go
  docs/configuration.md
  eth2util/deposit/deposit.go
  eth2util/deposit/deposit_internal_test.go
  eth2util/deposit/deposit_test.go
Labels: electra

#3536 *: support v1 endpoints on electra
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/eth2wrap_test.go
  app/eth2wrap/genwrap/genwrap.go
  app/eth2wrap/httpwrap.go
  app/eth2wrap/mocks/client.go
  app/eth2wrap/success.go
  core/bcast/bcast.go
  core/bcast/bcast_test.go
  core/dutydb/memory.go
  core/dutydb/memory_internal_test.go
  core/dutydb/memory_test.go
  core/eth2signeddata.go
  core/fetcher/fetcher.go
  core/fetcher/fetcher_test.go
  core/interfaces.go
  core/proto.go
  core/signeddata.go
  core/tracing.go
  core/tracker/inclusion.go
  core/tracker/inclusion_internal_test.go
  core/unsigneddata.go
  core/validatorapi/router.go
  core/validatorapi/router_internal_test.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_test.go
  eth2util/signing/signing.go
  go.mod
  go.sum
  testutil/beaconmock/beaconmock.go
  testutil/beaconmock/beaconmock_fuzz.go
  testutil/beaconmock/beaconmock_test.go
  testutil/beaconmock/options.go
  testutil/random.go
  testutil/validatormock/attest.go
  testutil/validatormock/propose_test.go
Labels: electra

#3535 ci: update golangci-lint name rule
  .golangci.yml
  app/errors/errors.go
  app/errors/go113.go
Labels: merge when ready

#3533 app/peerinfo: reduce nickname mapping logs
  app/peerinfo/peerinfo.go
Labels: merge when ready

#3534 eth2util: fix beacon node headers validation/parsing
  eth2util/helpers.go
  eth2util/helpers_test.go
Labels: merge when ready

#3524 cmd: fixed loaded keys ordering
  cmd/createcluster.go
Labels: merge when ready

#3539 *: support v2 calls for deneb fork
  core/dutydb/memory.go
  core/tracing.go
  core/validatorapi/validatorapi.go
Labels: electra

#3538 feat: add fallback beacon node metric
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_test.go
  app/eth2wrap/valcache_test.go
  docs/metrics.md
Labels: merge when ready

#3513 *: fix some function names in comment
  dkg/frost.go
  eth2util/helpers.go
Labels: merge when ready

#3556 app: add nickname label to metrics
  app/app.go
  app/peerinfo/metrics.go
  docs/metrics.md
Labels: merge when ready

#3566 app: v1.3-rc1
  app/version/version.go
Labels: branch-release
