Repository ObolNetwork/charon, pull requests merged in 2025-01, with the labels that each got.

#3342 app/eth2wrap: fallback beacon nodes
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/fallback.go
  app/eth2wrap/fallback_internal_test.go
  app/eth2wrap/genwrap/genwrap.go
  app/eth2wrap/multi.go
  app/eth2wrap/multi_test.go
Labels: merge when ready

#3428 app/peerinfo: add nickname field to peerinfo protocol
  app/app.go
  app/peerinfo/adhoc_test.go
  app/peerinfo/metrics.go
  app/peerinfo/peerinfo.go
  app/peerinfo/peerinfo_internal_test.go
  app/peerinfo/peerinfo_test.go
  app/peerinfo/peerinfopb/v1/peerinfo.pb.go
  app/peerinfo/peerinfopb/v1/peerinfo.proto
  cmd/run.go
  dkg/dkg.go
  docs/configuration.md
  docs/metrics.md
Labels: merge when ready

#3431 core/validatorapi: v1/v2 endpoints warning
  core/validatorapi/router.go
Labels: merge when ready

#3417 app: eth2wrap latency logging
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/genwrap/genwrap.go
  app/eth2wrap/multi.go
Labels: merge when ready

#3444 *: bump linter to 1.63.4
  .github/workflows/golangci-lint.yml
  .pre-commit/run_linter.sh
  cmd/test.go
  cmd/testbeacon.go
  cmd/testinfra.go
  cmd/testmev.go
  cmd/testpeers.go
  cmd/testpeers_internal_test.go
  cmd/testvalidator.go
  core/validatorapi/validatorapi_test.go
  go.mod
  testutil/compose/fuzz/fuzz_test.go
  testutil/integration/simnet_test.go
Labels: merge when ready

#3455 build: allow golangci-lint parallel on .pre-commit
  .pre-commit/run_linter.sh
Labels: merge when ready

#3441 fix: chown -R runner:docker 001 folder
  testutil/compose/auto.go
Labels: merge when ready

#3452 docs: contributing discord channel
  docs/contributing.md
Labels: merge when ready

#3438 *: trigger dispatch for LCDVN and Launchpad
  .github/workflows/release.yml
Labels: merge when ready, cicd

#3465 *: bumped protoc to fix pre-commit
  app/log/loki/lokipb/v1/loki.pb.go
  app/peerinfo/peerinfopb/v1/peerinfo.pb.go
  app/protonil/testdata/v1/test.pb.go
  buf.yaml
  cluster/manifestpb/v1/manifest.pb.go
  core/corepb/v1/consensus.pb.go
  core/corepb/v1/core.pb.go
  core/corepb/v1/parsigex.pb.go
  core/corepb/v1/priority.pb.go
  dkg/dkgpb/v1/bcast.pb.go
  dkg/dkgpb/v1/frost.pb.go
  dkg/dkgpb/v1/nodesigs.pb.go
  dkg/dkgpb/v1/sync.pb.go
Labels: merge when ready

#3467 app/peerinfo: fix race condition on storing nicknames
  app/peerinfo/peerinfo.go
Labels: merge when ready

#3468 *: label PRs to electra branch
  .github/workflows/label-pr.yml
  .github/workflows/nightly-tests.yml
  .github/workflows/test.yml
Labels: electra

#3470 core/consensus: change exponential timer for linear timer
  app/featureset/featureset.go
  app/featureset/featureset_internal_test.go
  core/consensus/utils/roundtimer.go
  core/consensus/utils/roundtimer_test.go
  docs/consensus.md
Labels: merge when ready

#3456 *: add custom target gas limit in cluster lock v1.10
  app/app.go
  app/obolapi/api_test.go
  cluster/cluster_internal_test.go
  cluster/cluster_test.go
  cluster/definition.go
  cluster/examples/cluster-definition-006.json
  cluster/lock.go
  cluster/manifest/cluster_test.go
  cluster/manifest/load_test.go
  cluster/manifest/mutationlegacylock.go
  cluster/manifestpb/v1/manifest.pb.go
  cluster/manifestpb/v1/manifest.proto
  cluster/ssz.go
  cluster/test_cluster.go
  cluster/testdata/cluster_definition_v1_10_0.json
  cluster/testdata/cluster_lock_v1_10_0.json
  cluster/version.go
  cmd/addvalidators.go
  cmd/createcluster.go
  cmd/createcluster_internal_test.go
  cmd/createdkg.go
  cmd/createdkg_internal_test.go
  cmd/testdata/TestCreateCluster_custom_target_gas_limit_files.golden
  cmd/testdata/TestCreateCluster_custom_target_gas_limit_output.golden
  cmd/testdata/Test_viewClusterManifest.golden
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_internal_test.go
  core/validatorapi/validatorapi_test.go
  dkg/dkg.go
  dkg/dkg_test.go
  docs/configuration.md
Labels: merge when ready

#3459 app/eth2wrap: add CLI support for fallback beacon node
  app/app.go
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/eth2wrap_test.go
  app/eth2wrap/fallback.go
  app/eth2wrap/fallback_internal_test.go
  app/eth2wrap/genwrap/genwrap.go
  app/eth2wrap/multi.go
  app/eth2wrap/multi_test.go
  app/eth2wrap/synthproposer_test.go
  cmd/exit.go
  cmd/exit_broadcast.go
  cmd/exit_broadcast_internal_test.go
  cmd/exit_fetch_internal_test.go
  cmd/exit_list.go
  cmd/exit_sign.go
  cmd/exit_sign_internal_test.go
  cmd/run.go
  core/scheduler/scheduler_test.go
  docs/configuration.md
Labels: merge when ready

#3485 *: bumped protoc to fix pre-commit
  app/log/loki/lokipb/v1/loki.pb.go
  app/peerinfo/peerinfopb/v1/peerinfo.pb.go
  app/protonil/testdata/v1/test.pb.go
  cluster/manifestpb/v1/manifest.pb.go
  core/corepb/v1/consensus.pb.go
  core/corepb/v1/core.pb.go
  core/corepb/v1/parsigex.pb.go
  core/corepb/v1/priority.pb.go
  dkg/dkgpb/v1/bcast.pb.go
  dkg/dkgpb/v1/frost.pb.go
  dkg/dkgpb/v1/nodesigs.pb.go
  dkg/dkgpb/v1/sync.pb.go
Labels: merge when ready

#3482 *: electra versioned aggregations
  app/eth2wrap/eth2wrap_gen.go
  app/eth2wrap/mocks/client.go
  app/eth2wrap/success.go
  core/bcast/bcast.go
  core/bcast/bcast_test.go
  core/dutydb/memory.go
  core/dutydb/memory_test.go
  core/eth2signeddata.go
  core/eth2signeddata_test.go
  core/fetcher/fetcher.go
  core/fetcher/fetcher_test.go
  core/interfaces.go
  core/parsigex/parsigex_test.go
  core/proto.go
  core/proto_test.go
  core/serialise_test.go
  core/signeddata.go
  core/signeddata_test.go
  core/ssz.go
  core/ssz_test.go
  core/testdata/TestJSONSerialisation_AggregatedAttestation.json.golden
  core/testdata/TestJSONSerialisation_SignedAggregateAndProof.json.golden
  core/testdata/TestJSONSerialisation_VersionedAggregatedAttestation.json.golden
  core/testdata/TestJSONSerialisation_VersionedSignedAggregateAndProof.json.golden
  core/testdata/TestSSZSerialisation_AggregatedAttestation.ssz.golden
  core/testdata/TestSSZSerialisation_SignedAggregateAndProof.ssz.golden
  core/testdata/TestSSZSerialisation_VersionedAggregatedAttestation.ssz.golden
  core/testdata/TestSSZSerialisation_VersionedSignedAggregateAndProof.ssz.golden
  core/tracker/inclusion.go
  core/tracker/inclusion_internal_test.go
  core/unsigneddata.go
  core/unsigneddata_test.go
  core/validatorapi/router.go
  core/validatorapi/router_internal_test.go
  core/validatorapi/validatorapi.go
  core/validatorapi/validatorapi_test.go
  eth2util/signing/signing.go
  go.mod
  go.sum
  testutil/beaconmock/beaconmock.go
  testutil/beaconmock/beaconmock_fuzz.go
  testutil/beaconmock/beaconmock_test.go
  testutil/beaconmock/options.go
  testutil/beaconmock/server.go
  testutil/fuzz.go
  testutil/integration/simnet_test.go
  testutil/random.go
  testutil/validatormock/attest.go
  testutil/validatormock/propose.go
  testutil/validatormock/propose_test.go
  testutil/validatormock/testdata/TestAttest_0_aggregations.golden
  testutil/validatormock/testdata/TestAttest_1_aggregations.golden
Labels: merge when ready, electra

#3490 *: update github actions
  .github/workflows/build-push-deploy-promrated.yaml
  .github/workflows/build-push-deploy.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/govulncheck.yml
  .github/workflows/nightly-tests.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .github/workflows/verify-pr.yml
Labels: merge when ready, cicd

#3489 cmd: fetch and broadcast all when not all are activated
  app/eth2wrap/eth2wrap.go
  app/eth2wrap/eth2wrap_test.go
  app/obolapi/api.go
  cmd/exit_broadcast.go
  cmd/exit_broadcast_internal_test.go
  cmd/exit_fetch.go
  cmd/exit_fetch_internal_test.go
Labels: merge when ready

#3491 cmd: update golden file after rebase
  cmd/testdata/TestCreateCluster_custom_target_gas_limit_files.golden
Labels: electra
